# Generated by Django 5.1.2 on 2025-09-28 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0010_remove_empresa_anexo_simples'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicosMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('servicos', models.CharField(max_length=200, verbose_name='Serviços')),
                ('porte_anestesico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Porte Anestésico')),
            ],
            options={
                'verbose_name': 'Serviço Médico',
                'verbose_name_plural': 'Serviços Médicos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Convênio')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_apartamento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Apartamento')),
                ('preco_enfermaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Enfermaria')),
                ('codigo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos_medicos.servicosmedicos', verbose_name='Código do Serviço')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos_medicos.convenio', verbose_name='Convênio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tabela de Preço',
                'verbose_name_plural': 'Tabelas de Preço',
                'ordering': ['empresa', 'convenio', 'codigo_servico'],
                'unique_together': {('empresa', 'convenio', 'codigo_servico')},
            },
        ),
    ]
