# Generated by Django 5.1.2 on 2025-09-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos_medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicosmedicos',
            name='porte_anestesico',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True, verbose_name='Porte Anestésico'),
        ),
    ]
