# Generated by Django 5.1.2 on 2025-09-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_remove_empresa_anexo_simples'),
        ('servicos_medicos', '0002_alter_servicosmedicos_porte_anestesico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tabela', models.CharField(max_length=100, verbose_name='Nome da Tabela')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos_medicos.convenio', verbose_name='Convênio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cabeçalho',
                'verbose_name_plural': 'Cabeçalhos',
                'ordering': ['empresa', 'convenio', 'nome_tabela'],
            },
        ),
    ]
