# Generated by Django 5.1.2 on 2025-09-28 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_remove_empresa_anexo_simples'),
        ('servicos_medicos', '0003_cabecalho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabelapreco',
            options={'ordering': ['empresa', 'convenio', 'cabecalho', 'codigo_servico'], 'verbose_name': 'Tabela de Preço', 'verbose_name_plural': 'Tabelas de Preço'},
        ),
        migrations.AlterUniqueTogether(
            name='tabelapreco',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tabelapreco',
            name='cabecalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos_medicos.cabecalho', verbose_name='Cabeçalho'),
        ),
        migrations.AlterUniqueTogether(
            name='tabelapreco',
            unique_together={('empresa', 'convenio', 'cabecalho', 'codigo_servico')},
        ),
    ]
