# Generated by Django 5.2.16 on 2026-08-04 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos_medicos', '0005_alter_tabelapreco_precos_contraste'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='dia_abertura',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês para abertura do convênio (1 a 31).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia para abertura'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='dia_fechamento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês para fechamento do convênio (1 a 31).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia para fechamento'),
        ),
    ]
