# Generated by Django 4.2.2 on 2025-08-15 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Conciliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('conta', models.CharField(blank=True, max_length=30, null=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extrato.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtratoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OFX', 'OFX'), ('PDF', 'PDF')], max_length=3)),
                ('arquivo', models.FileField(upload_to='extratos/')),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='extrato.contabancaria')),
            ],
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='extrato.empresa'),
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('documento', models.CharField(blank=True, max_length=60, null=True)),
                ('historico', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('conciliado', models.BooleanField(default=False)),
                ('origem', models.CharField(default='MANUAL', max_length=20)),
                ('hash_unico', models.CharField(db_index=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extrato.banco')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='extrato.contabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='extrato.empresa')),
                ('idconciliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extrato.conciliacao')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'conta', 'data'], name='extrato_lan_empresa_46b7ba_idx'), models.Index(fields=['conciliado'], name='extrato_lan_concili_3803b1_idx'), models.Index(fields=['hash_unico'], name='extrato_lan_hash_un_a5d878_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='lancamento',
            constraint=models.UniqueConstraint(fields=('conta', 'data', 'documento', 'valor', 'historico'), name='uniq_lancamento_basico'),
        ),
        migrations.AlterUniqueTogether(
            name='contabancaria',
            unique_together={('empresa', 'banco', 'agencia', 'conta')},
        ),
    ]
