# Generated by Django 4.2.23 on 2025-08-15 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_options_empresa_data_atualizacao_and_more'),
        ('extrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='empresa.empresa'),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
