# Generated by Django 5.1.2 on 2025-09-16 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0006_contasapagar_cobranca_contasapagar_contabanco_and_more'),
        ('contasareceber', '0003_baixacontaareceber'),  # Garante que BaixaContaAReceber existe antes do FK
        ('empresa', '0001_initial'),
        ('extrato', '0002_alter_contabancaria_empresa_alter_lancamento_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtratoMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_baixa', models.DateField(verbose_name='Data da Baixa')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('situacao', models.CharField(choices=[('recebido', 'Recebido'), ('pago', 'Pago'), ('estornado', 'Estornado'), ('cancelado', 'Cancelado')], default='recebido', max_length=20, verbose_name='Situação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Pago/Recebido')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('baixa_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extrato_movimentos', to='contasareceber.baixacontaareceber')),
                ('conta_banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extrato_movimentos', to='extrato.contabancaria')),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extrato_movimentos', to='contasapagar.contasapagar')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extrato_movimentos', to='contasareceber.contaareceber')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrato_movimentos', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Movimento do Extrato',
                'verbose_name_plural': 'Movimentos do Extrato',
                'ordering': ['-data_baixa', '-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'data_baixa'], name='extrato_ext_empresa_94231b_idx'), models.Index(fields=['situacao'], name='extrato_ext_situaca_790fa8_idx'), models.Index(fields=['conta_receber'], name='extrato_ext_conta_r_7c816f_idx'), models.Index(fields=['conta_pagar'], name='extrato_ext_conta_p_fd10a1_idx')],
            },
        ),
    ]
