# Generated by Django 5.1.2 on 2025-09-16 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0003_extratomovimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratomovimento',
            name='conta_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extrato_movimentos', to='extrato.contabancaria'),
        ),
    ]
