# Generated by Django 5.1.2 on 2025-09-17 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('extrato', '0004_alter_extratomovimento_conta_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratomovimento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extrato_movimentos', to='categoria.categoria'),
        ),
    ]
