# Generated by Django 5.1.2 on 2025-09-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_empresa_utiliza_iss_fixo'),
        ('extrato', '0005_extratomovimento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='fitid',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['fitid'], name='extrato_lan_fitid_9295ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='lancamento',
            constraint=models.UniqueConstraint(fields=('conta', 'fitid'), name='uniq_lancamento_fitid'),
        ),
    ]
