# Generated by Django 5.1.2 on 2025-09-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0006_lancamento_fitid_lancamento_saldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
