# Generated by Django 5.1.2 on 2025-09-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0007_banco_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logobanco/', verbose_name='Logo'),
        ),
    ]
