# Generated by Django 5.1.2 on 2025-09-17 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0008_banco_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratomovimento',
            name='lancamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extrato_movimentos', to='extrato.lancamento'),
        ),
    ]
