# Generated by Django 5.1.2 on 2025-09-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0009_extratomovimento_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], default='A', max_length=1, verbose_name='Status'),
        ),
    ]
