# Generated by Django 5.1.2 on 2025-09-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0010_contabancaria_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contabancaria',
            table='contabanco_contabanco',
        ),
    ]
