# Generated by Django 5.1.2 on 2025-09-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0012_add_contabancaria_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='tipo',
        ),
    ]
