# Generated by Django 5.1.2 on 2025-09-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0013_remove_contabancaria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='tipo',
            field=models.CharField(choices=[('CAIXA', 'Caixa'), ('CONTA_CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Poupança'), ('INVESTIMENTO', 'Investimento'), ('EMPRESTIMO', 'Empréstimo'), ('FATURA_CARTAO', 'Fatura de Cartão')], default='CONTA_CORRENTE', max_length=20, verbose_name='Tipo'),
        ),
    ]
