# Generated by Django 5.1.2 on 2025-09-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0014_contabancaria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratomovimento',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Saldo'),
        ),
    ]
