# Generated by Django 5.1.2 on 2025-09-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0015_alter_extratomovimento_saldo'),
    ]

    operations = [
        # Recriar a foreign key usando AlterField - Django vai gerar o SQL correto
        migrations.AlterField(
            model_name='extratomovimento',
            name='conta_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extrato_movimentos', to='extrato.contabancaria', verbose_name='Conta Bancária'),
        ),
    ]
