# Generated by Django 5.1.2 on 2025-09-25 19:11

from django.db import migrations, connection


def apply_mysql_constraints(apps, schema_editor):
    """Só executa no MySQL; SQLite não suporta ADD/DROP FOREIGN KEY."""
    if connection.vendor != "mysql":
        return
    with connection.cursor() as cursor:
        try:
            cursor.execute(
                "ALTER TABLE extrato_extratomovimento DROP FOREIGN KEY extrato_extratomovim_conta_banco_id_0c40a4ce_fk_contabanc;"
            )
        except Exception:
            pass  # constraint pode não existir
        cursor.execute(
            "ALTER TABLE extrato_extratomovimento ADD CONSTRAINT extrato_extratomovim_conta_banco_id_0c40a4ce_fk_contabanc "
            "FOREIGN KEY (conta_banco_id) REFERENCES contabanco_contabanco(id);"
        )


def reverse_mysql_constraints(apps, schema_editor):
    if connection.vendor != "mysql":
        return
    with connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE extrato_extratomovimento DROP FOREIGN KEY extrato_extratomovim_conta_banco_id_0c40a4ce_fk_contabanc;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0016_fix_extratomovimento_foreign_key'),
    ]

    operations = [
        # MySQL: ajuste de constraints. SQLite: no-op.
        migrations.RunPython(apply_mysql_constraints, reverse_mysql_constraints),
    ]
