# Generated by Django 5.1.2 on 2025-09-25 19:29

from django.db import migrations, connection


def apply_mysql_constraints(apps, schema_editor):
    """Só executa no MySQL; SQLite não suporta essas operações."""
    if connection.vendor != "mysql":
        return
    with connection.cursor() as cursor:
        cursor.execute("SET FOREIGN_KEY_CHECKS = 0;")
        try:
            cursor.execute(
                "ALTER TABLE contasareceber_baixacontaareceber ADD CONSTRAINT contasareceber_baixa_conta_banco_id_f462de09_fk_contabanc "
                "FOREIGN KEY (conta_banco_id) REFERENCES contabanco_contabanco(id);"
            )
        except Exception:
            pass
        try:
            cursor.execute(
                "ALTER TABLE extrato_extratomovimento ADD CONSTRAINT extrato_extratomovim_conta_banco_id_0c40a4ce_fk_contabanc "
                "FOREIGN KEY (conta_banco_id) REFERENCES contabanco_contabanco(id);"
            )
        except Exception:
            pass
        cursor.execute("SET FOREIGN_KEY_CHECKS = 1;")


def reverse_mysql_constraints(apps, schema_editor):
    if connection.vendor != "mysql":
        return


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0017_fix_constraints_simple'),
    ]

    operations = [
        migrations.RunPython(apply_mysql_constraints, reverse_mysql_constraints),
    ]
