# Generated by Django 4.2.2 on 2025-10-01 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0019_add_conta_contabil_to_contabancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratomovimento',
            name='conta_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extrato_movimentos', to='extrato.contabancaria'),
        ),
    ]
