# Generated by Django 5.1.2 on 2025-10-24 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0020_alter_extratomovimento_conta_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='lancamento_origem_transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_destino_transferencia', to='extrato.lancamento'),
        ),
    ]
