# Generated by Django 5.2.16 on 2026-08-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0025_contabancaria_sicoob_numero_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='conta_azul_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='ID Conta Azul'),
        ),
    ]
