# Generated by Django 5.2.16 on 2026-09-19 20:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
        ('estoque', '0001_produto_estoque_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('aberto', models.BooleanField(default=True, verbose_name='Aberto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50, verbose_name='Código')),
                ('descricao_produto', models.CharField(max_length=300, verbose_name='Produto')),
                ('quantidade_estoque', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Qtd. estoque (sistema)')),
                ('contagem_1', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='1ª contagem')),
                ('contagem_1_em', models.DateTimeField(blank=True, null=True)),
                ('contagem_2', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='2ª contagem')),
                ('contagem_2_em', models.DateTimeField(blank=True, null=True)),
                ('contagem_3', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='3ª contagem')),
                ('contagem_3_em', models.DateTimeField(blank=True, null=True)),
                ('contagem_1_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_contagens_1', to=settings.AUTH_USER_MODEL)),
                ('contagem_2_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_contagens_2', to=settings.AUTH_USER_MODEL)),
                ('contagem_3_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_contagens_3', to=settings.AUTH_USER_MODEL)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventario.inventario', verbose_name='Inventário')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_inventario', to='estoque.produtoestoque', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do inventário',
                'verbose_name_plural': 'Itens do inventário',
                'ordering': ['codigo_produto', 'descricao_produto'],
                'constraints': [models.UniqueConstraint(fields=('inventario', 'codigo_produto'), name='inventario_item_codigo_unico')],
            },
        ),
        migrations.CreateModel(
            name='InventarioResponsavelContagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Rodada')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis_contagem', to='inventario.inventario', verbose_name='Inventário')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_contagens_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Responsável pela contagem',
                'verbose_name_plural': 'Responsáveis pelas contagens',
                'constraints': [models.UniqueConstraint(fields=('inventario', 'rodada', 'usuario'), name='inventario_responsavel_unico_rodada_usuario')],
            },
        ),
    ]
