# Generated by Django 5.2.16 on 2026-09-19 21:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
        ('estoque', '0002_quantidade_estoque_contabil'),
        ('inventario', '0001_inventario_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='estoque_aplicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='estoque_aplicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_estoque_aplicado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventario',
            name='rodada_atualiza_estoque',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = nenhuma; 1, 2 ou 3 = contagem usada para aplicar no estoque.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Rodada que atualiza o estoque'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='quantidade_estoque_contabil',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Est. contábil (sistema)'),
        ),
        migrations.CreateModel(
            name='EstoqueBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_estoque_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups_estoque', to='empresa.empresa')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups_estoque', to='inventario.inventario', verbose_name='Inventário')),
            ],
            options={
                'verbose_name': 'Backup de estoque',
                'verbose_name_plural': 'Backups de estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueBackupLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=300)),
                ('marca', models.CharField(blank=True, default='', max_length=120)),
                ('quantidade_estoque', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantidade_estoque_contabil', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('valor_ultima_compra', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('valor_custo_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('valor_custo_contabil', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='inventario.estoquebackup')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produtoestoque')),
            ],
            options={
                'verbose_name': 'Linha do backup de estoque',
                'verbose_name_plural': 'Linhas do backup de estoque',
                'ordering': ['codigo_produto'],
            },
        ),
    ]
