# Generated by Django 5.2.16 on 2026-09-19 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50, verbose_name='Código do produto')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição do produto')),
                ('marca', models.CharField(blank=True, default='', max_length=120, verbose_name='Marca')),
                ('quantidade_estoque', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantidade em estoque')),
                ('valor_ultima_compra', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Valor da última compra')),
                ('valor_custo_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Valor custo médio')),
                ('valor_custo_contabil', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Valor custo contábil')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_estoque', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Produto (estoque)',
                'verbose_name_plural': 'Produtos (estoque)',
                'ordering': ['codigo_produto', 'descricao'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo_produto'), name='produto_estoque_codigo_unico_empresa')],
            },
        ),
    ]
