# Generated by Django 5.2.16 on 2026-09-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_produto_estoque_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoestoque',
            name='quantidade_estoque_contabil',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Estoque contábil'),
        ),
    ]
