# Generated by Django 4.2.2 on 2023-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtparcelas', models.CharField(max_length=2, verbose_name='Nº Parcelas')),
                ('intervaloparcelas', models.CharField(max_length=4, verbose_name='Intervalo de dias Parcela')),
                ('tipo', models.CharField(choices=[('A', 'A VISTA'), ('P', 'A PRAZO')], default='A', max_length=1, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descricao')),
            ],
        ),
    ]
