# Generated by Django 4.2.2 on 2023-09-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapgto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContaBanco',
            new_name='FormaPgto',
        ),
    ]
