# Generated by Django 4.2.2 on 2023-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapgto', '0002_rename_contabanco_formapgto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapgto',
            name='tipo',
            field=models.CharField(choices=[('0', 'A VISTA'), ('1', 'A PRAZO')], default='A', max_length=1, verbose_name='Tipo'),
        ),
    ]
