# Generated by Django 4.2.2 on 2025-08-14 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_options_empresa_data_atualizacao_and_more'),
        ('formapgto', '0003_alter_formapgto_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formapgto',
            options={'ordering': ['descricao'], 'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
        migrations.AddField(
            model_name='formapgto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='formapgto',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='formapgto',
            name='intervaloparcelas',
            field=models.CharField(default='0', max_length=2, verbose_name='Intervalo entre Parcelas'),
        ),
        migrations.AlterField(
            model_name='formapgto',
            name='qtparcelas',
            field=models.CharField(default='1', max_length=2, verbose_name='Quantidade de Parcelas'),
        ),
        migrations.AlterField(
            model_name='formapgto',
            name='tipo',
            field=models.CharField(choices=[('0', 'A Vista'), ('1', 'A Prazo')], default='0', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='formapgto',
            unique_together={('empresa', 'descricao')},
        ),
    ]
