# Generated by Django 5.1.2 on 2025-10-31 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('empresa', '0001_initial'),
        ('formapgto', '0001_initial'),
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraConciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definicao_historico', models.CharField(max_length=255, verbose_name='Definição para Histórico')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria', verbose_name='Categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapgto.formapgto', verbose_name='Forma de Pagamento')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Regra de Conciliação',
                'verbose_name_plural': 'Regras de Conciliação',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
