# Generated by Django 5.1.2 on 2025-10-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regraConciliacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraconciliacao',
            name='descricao',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição'),
        ),
    ]
