# Generated by Django 5.1.2 on 2025-10-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regraConciliacao', '0002_regraconciliacao_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraconciliacao',
            name='tipo_conciliacao',
            field=models.CharField(choices=[('conciliacao', 'Conciliação'), ('transferencia', 'Transferência')], default='conciliacao', max_length=20, verbose_name='Tipo de Conciliação'),
        ),
    ]
