# Generated by Django 5.1.2 on 2025-10-31 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('regraConciliacao', '0003_regraconciliacao_tipo_conciliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraconciliacao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='regraconciliacao',
            name='tipo_lancamento',
            field=models.CharField(choices=[('contas_pagar', 'Contas a Pagar'), ('contas_receber', 'Contas a Receber')], default='contas_pagar', max_length=20, verbose_name='Tipo de Lançamento'),
        ),
    ]
