# Generated by Django 5.1.2 on 2025-10-31 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0021_lancamento_lancamento_origem_transferencia'),
        ('regraConciliacao', '0004_regraconciliacao_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraconciliacao',
            name='banco_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extrato.banco', verbose_name='Banco Destino'),
        ),
    ]
