# Generated by Django 5.1.2 on 2025-10-31 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0021_lancamento_lancamento_origem_transferencia'),
        ('regraConciliacao', '0005_regraconciliacao_banco_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regraconciliacao',
            name='banco_destino',
        ),
        migrations.AddField(
            model_name='regraconciliacao',
            name='conta_bancaria_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extrato.contabancaria', verbose_name='Conta Bancária Destino'),
        ),
    ]
