# Generated by Django 5.1.2 on 2025-11-01 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0008_auto_20251024_2048'),
        ('formapgto', '0004_alter_formapgto_options_formapgto_empresa_and_more'),
        ('regraConciliacao', '0006_remove_regraconciliacao_banco_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regraconciliacao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='regraconciliacao',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formapgto.formapgto', verbose_name='Forma de Pagamento'),
        ),
    ]
