# Generated by Django 4.2.2 on 2026-07-24 13:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receitas'), ('fixa', 'Despesas fixas'), ('semi_fixa', 'Despesas semi-fixas'), ('variavel', 'Despesas variáveis'), ('imposto', 'Impostos')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('forma_calculo', models.CharField(choices=[('fixo', 'Valor fixo / previsto'), ('percentual', '% sobre receitas')], default='fixo', max_length=20, verbose_name='Forma de cálculo')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Usado quando a forma é valor fixo/previsto.', max_digits=15, verbose_name='Valor mensal previsto')),
                ('valor_min', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Faixa típica (semi-fixas).', max_digits=15, verbose_name='Valor mínimo')),
                ('valor_max', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Faixa típica (semi-fixas).', max_digits=15, verbose_name='Valor máximo')),
                ('aliquota_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Para impostos ou variáveis sobre faturamento/receitas.', max_digits=8, verbose_name='Alíquota (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_orcamento', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Item orçamentário',
                'verbose_name_plural': 'Itens orçamentários',
                'ordering': ['tipo', 'ordem', 'nome'],
            },
        ),
    ]
