# Generated by Django 4.2.2 on 2026-07-24 14:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
        ('planejamento_orcamentario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Data do primeiro lançamento. Os demais repetem no mesmo dia nos meses seguintes.', null=True, verbose_name='Data do mês inicial'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='qtd_meses',
            field=models.PositiveIntegerField(default=1, help_text='Quantos meses o lançamento deve se repetir (incluindo o mês inicial).', verbose_name='Quantidade de meses'),
        ),
        migrations.CreateModel(
            name='LancamentoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField(db_index=True, verbose_name='Data do lançamento')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Valor')),
                ('sequencia', models.PositiveIntegerField(default=1, verbose_name='Sequência')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_orcamento', to='empresa.empresa', verbose_name='Empresa')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='planejamento_orcamentario.itemorcamento', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Lançamento orçamentário',
                'verbose_name_plural': 'Lançamentos orçamentários',
                'ordering': ['data_lancamento', 'sequencia'],
                'indexes': [models.Index(fields=['empresa', 'data_lancamento'], name='planejament_empresa_819a5b_idx')],
            },
        ),
    ]
