# Generated by Django 4.2.2 on 2026-07-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0009_alter_categoria_classificacao'),
        ('planejamento_orcamentario', '0002_itemorcamento_data_inicio_itemorcamento_qtd_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_orcamento', to='categoria.categoria', verbose_name='Categoria'),
        ),
    ]
