# Generated by Django 5.2.16 on 2026-08-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento_orcamentario', '0003_itemorcamento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorcamento',
            name='forma_calculo',
            field=models.CharField(choices=[('fixo', 'Valor fixo / previsto'), ('percentual', '% sobre receitas'), ('presumido_irpj', 'Lucro Presumido — IRPJ (mensal)'), ('presumido_csll', 'Lucro Presumido — CSLL (mensal)')], default='fixo', max_length=20, verbose_name='Forma de cálculo'),
        ),
    ]
