server {
    listen 80;
    listen [::]:80;
    server_name saudefinanceira.local 10.10.1.61;
    return 301 https://$host$request_uri;

}


server {

    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name saudefinanceira.local 10.10.1.61;

    ssl_certificate     /etc/nginx/ssl/saudefinanceira.local.crt;
    ssl_certificate_key /etc/nginx/ssl/saudefinanceira.local.key;


   
    location /static/ { 

        alias /var/www/html/SaudeFinanceira/staticfiles/;
        expires 30d; 
        access_log off; 
     
    }

    # 2. Arquivos de Mídia (Media Files - Uploads)
    location /media/ { 

        alias /var/www/html/SaudeFinanceira/media/;
        expires 30d;
        access_log off;

    }



    # 3. Proxy Reverso para o Gunicorn (tráfego da aplicação)
    location / {
        # Use o upstream definido no início
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8000;
        
        proxy_read_timeout 60; 
    }
    
    # Adicionando um tratamento de erro para o favicon
    location = /favicon.ico { access_log off; log_not_found off; }

}
