# Generated by Django 5.1.2 on 2025-09-19 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioRecebiveisMaquinaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('bandeira', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bandeira')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Bruto')),
                ('taxa_maquinha', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de Maquinha')),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Líquido')),
                ('maquinha', models.CharField(blank=True, max_length=50, null=True, verbose_name='Maquinha')),
                ('numero_autorizacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Autorização')),
                ('data_venda', models.DateField(blank=True, null=True, verbose_name='Data da Venda')),
                ('nsu_doc', models.CharField(blank=True, max_length=50, null=True, verbose_name='NSU/DOC')),
                ('parcelas', models.IntegerField(default=1, verbose_name='Parcelas')),
                ('total_parcelas', models.IntegerField(default=1, verbose_name='Total Parcelas')),
                ('conciliado', models.BooleanField(default=False, verbose_name='Conciliado')),
                ('identificacao_extrato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificação Extrato')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal')),
                ('razao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Relatório de Recebíveis Máquina de Cartão',
                'verbose_name_plural': 'Relatórios de Recebíveis Máquina de Cartão',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
