# Generated by Django 5.1.2 on 2025-09-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatoriorecebiveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriorecebiveismaquinacartao',
            name='maquinha',
            field=models.CharField(blank=True, choices=[('SIPAG', 'SIPAG'), ('CIELO', 'CIELO'), ('INFINTY', 'INFINTY'), ('GETNET', 'GETNET'), ('SAFRAPAY', 'SAFRAPAY'), ('SUMUP', 'SUMUP'), ('PAGBANK', 'PAGBANK'), ('STONE', 'STONE'), ('MERCADOPAGO', 'MERCADOPAGO'), ('OUTROS', 'OUTROS')], max_length=50, null=True, verbose_name='Maquinha'),
        ),
    ]
