# Generated by Django 5.1.2 on 2025-09-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatoriorecebiveis', '0002_alter_relatoriorecebiveismaquinacartao_maquinha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriorecebiveismaquinacartao',
            name='data_venda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data da Venda'),
        ),
    ]
