# Generated by Django 5.1.2 on 2025-09-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatoriorecebiveis', '0003_alter_relatoriorecebiveismaquinacartao_data_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriorecebiveismaquinacartao',
            name='conta_bancaria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Conta Bancária'),
        ),
    ]
