# Generated by Django 5.1.2 on 2025-09-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasareceber', '0008_alter_contaareceber_status'),
        ('relatoriorecebiveis', '0004_relatoriorecebiveismaquinacartao_conta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriorecebiveismaquinacartao',
            name='conta_a_receber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contasareceber.contaareceber', verbose_name='Conta a Receber'),
        ),
    ]
