# Generated by Django 5.1.2 on 2025-09-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatoriorecebiveis', '0005_relatoriorecebiveismaquinacartao_conta_a_receber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriorecebiveismaquinacartao',
            name='conta_bancaria',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Conta Bancária'),
        ),
    ]
