# Generated by Django 5.1.2 on 2025-09-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatoriorecebiveis', '0006_alter_relatoriorecebiveismaquinacartao_conta_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriorecebiveismaquinacartao',
            name='conta_bancaria',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Conta Bancária'),
        ),
    ]
