# Generated by Django 5.1.2 on 2025-10-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatoriorecebiveis', '0008_auto_20251027_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriorecebiveismaquinacartao',
            name='conciliado',
            field=models.CharField(choices=[(False, 'Não Conciliado'), ('parcial', 'Conciliado com Contas a Receber'), (True, 'Conciliado com Extrato')], default=False, max_length=10, verbose_name='Conciliado'),
        ),
    ]
