# Generated by Django 5.1.2 on 2025-10-28 00:29

from django.db import migrations, models, connection


def convert_conciliado_values(apps, schema_editor):
    """Converte valores string para boolean no campo conciliado usando SQL direto"""
    with connection.cursor() as cursor:
        # Converte 'parcial' para 0 (False)
        cursor.execute("UPDATE relatoriorecebiveis_relatoriorecebiveismaquinacartao SET conciliado = 0 WHERE conciliado = 'parcial'")
        # Converte 'False' para 0 (False)
        cursor.execute("UPDATE relatoriorecebiveis_relatoriorecebiveismaquinacartao SET conciliado = 0 WHERE conciliado = 'False'")
        # Converte 'True' para 1 (True)
        cursor.execute("UPDATE relatoriorecebiveis_relatoriorecebiveismaquinacartao SET conciliado = 1 WHERE conciliado = 'True'")


class Migration(migrations.Migration):

    dependencies = [
        ('relatoriorecebiveis', '0009_auto_20251027_1845'),
    ]

    operations = [
        migrations.RunPython(convert_conciliado_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='relatoriorecebiveismaquinacartao',
            name='conciliado',
            field=models.BooleanField(default=False, verbose_name='Conciliado'),
        ),
    ]
