# Generated by Django 5.2.16 on 2026-07-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendador_tarefas', '0003_tarefas_verificar_glosa_mensal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tarefaagendada',
            new_name='agendador_t_empresa_96cf94_idx',
            old_name='agendador_t_empresa_7a0f0d_idx',
        ),
    ]
