# Generated by Django 5.2.16 on 2026-08-01 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendador_tarefas', '0014_corrigir_repasse_anestesia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Trâmite')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_tarefa', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='agendador_tarefas.tarefaagendada', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Trâmite da tarefa',
                'verbose_name_plural': 'Trâmites das tarefas',
                'ordering': ['criado_em'],
            },
        ),
    ]
