# Generated by Django 4.2.2 on 2023-09-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='sintetico',
            field=models.CharField(default=1, max_length=1, verbose_name='sintetico'),
            preserve_default=False,
        ),
    ]
