# Generated by Django 4.2.2 on 2023-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_sintetico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='sintetico',
            field=models.CharField(choices=[('A', 'ANALITICO'), ('S', 'SINTETICO')], default='A', max_length=1, verbose_name='sintetico'),
        ),
    ]
