# Generated by Django 4.2.2 on 2023-10-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_alter_categoria_sintetico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='classificacao',
            field=models.CharField(error_messages='Classificacao validacao', max_length=30, verbose_name='Classificacao'),
        ),
    ]
