# Generated by Django 5.1.2 on 2025-09-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0004_alter_categoria_classificacao'),
        ('empresa', '0005_empresa_utiliza_iss_fixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa'),
        ),
    ]
