# Generated by Django 5.1.2 on 2025-09-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0005_categoria_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='grupo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo'),
        ),
    ]
