# Generated by Django 5.1.2 on 2025-09-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0006_categoria_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('R', 'RECEITA'), ('D', 'DESPESAS'), ('I', 'INVESTIMENTO'), ('L', 'DISTRIBUICAO DE LUCRO')], default='D', max_length=1, verbose_name='Tipo'),
        ),
    ]
