# Generated by Django 5.1.2 on 2025-10-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0007_categoria_tipo'),
    ]

    operations = [
    ]
