# Generated by Django 4.2.2 on 2026-03-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0008_auto_20251024_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='classificacao',
            field=models.CharField(max_length=30, verbose_name='Classificacao'),
        ),
    ]
