# Generated by Django 5.2.16 on 2026-08-01 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0009_alter_categoria_classificacao'),
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='conta_azul_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='ID Conta Azul'),
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_azul_id', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo', models.CharField(blank=True, default='', max_length=60)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_custo', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Centro de custo',
                'verbose_name_plural': 'Centros de custo',
                'constraints': [models.UniqueConstraint(condition=models.Q(('conta_azul_id__gt', '')), fields=('empresa', 'conta_azul_id'), name='centro_custo_conta_azul_unico')],
            },
        ),
    ]
