# Generated by Django 4.2.2 on 2026-08-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0011_categoria_bloquear_sync_conta_azul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='grupo',
            field=models.CharField(blank=True, help_text='Categoria pai no Conta Azul (campo "Aparecer dentro da categoria").', max_length=100, null=True, verbose_name='Grupo'),
        ),
    ]
