# Generated by Django 5.1.2 on 2025-09-16 01:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0005_empresa_utiliza_iss_fixo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturamentoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('guia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Guia')),
                ('carteirinha', models.CharField(blank=True, max_length=50, null=True, verbose_name='Carteirinha')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome')),
                ('codigo_servico', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Serviço')),
                ('servico', models.CharField(blank=True, max_length=200, null=True, verbose_name='Serviço')),
                ('data_autorizacao', models.DateField(blank=True, null=True, verbose_name='Data da Autorização')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('porte', models.CharField(blank=True, max_length=20, null=True, verbose_name='Porte')),
                ('qt', models.IntegerField(default=1, verbose_name='QT')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local')),
                ('medico', models.CharField(blank=True, max_length=200, null=True, verbose_name='Médico')),
                ('anestesista', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anestesista')),
                ('convenio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Convênio')),
                ('receber_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Receber Por')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('guia_lancada', models.BooleanField(default=False, verbose_name='Guia Lançada')),
                ('codigo_relatorio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Relatório')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Faturamento Médico',
                'verbose_name_plural': 'Faturamentos Médicos',
                'ordering': ['-data', '-data_criacao'],
            },
        ),
    ]
