# Generated by Django 5.1.2 on 2025-09-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamentomedico',
            name='numero_guia_lancada',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Guia Lançada'),
        ),
    ]
