# Generated by Django 5.1.2 on 2025-09-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0002_faturamentomedico_numero_guia_lancada'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamentomedico',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal'),
        ),
    ]
