# Generated by Django 5.1.2 on 2025-09-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0003_faturamentomedico_nota_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamentomedico',
            name='guia_lancada',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Guia Lançada'),
        ),
    ]
