# Generated by Django 5.1.2 on 2025-09-16 03:32

import django.db.models.deletion
import faturamento_medico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0004_alter_faturamentomedico_guia_lancada'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAnexado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Selecione o arquivo a ser anexado', upload_to=faturamento_medico.models.documento_upload_path, verbose_name='Arquivo')),
                ('nome', models.CharField(blank=True, help_text='Nome descritivo do documento (opcional)', max_length=200, verbose_name='Nome do Documento')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do documento (opcional)', null=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexados', to='faturamento_medico.faturamentomedico', verbose_name='Faturamento')),
            ],
            options={
                'verbose_name': 'Documento Anexado',
                'verbose_name_plural': 'Documentos Anexados',
                'ordering': ['-data_upload'],
            },
        ),
    ]
