# Generated by Django 5.1.2 on 2025-09-16 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0005_documentoanexado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_servico', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Serviço')),
                ('servico', models.CharField(blank=True, max_length=200, null=True, verbose_name='Serviço')),
                ('porte', models.CharField(blank=True, max_length=20, null=True, verbose_name='Porte')),
                ('qt', models.IntegerField(default=1, verbose_name='QT')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_servico', to='faturamento_medico.faturamentomedico', verbose_name='Faturamento')),
            ],
            options={
                'verbose_name': 'Item de Serviço',
                'verbose_name_plural': 'Itens de Serviço',
                'ordering': ['data_criacao'],
            },
        ),
    ]
