# Generated by Django 5.1.2 on 2025-09-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0006_itemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamentomedico',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
    ]
