# Generated by Django 5.1.2 on 2025-09-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0007_faturamentomedico_data_fechamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código do Serviço')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Serviço')),
                ('porte', models.CharField(blank=True, max_length=50, null=True, verbose_name='Porte ANESTÉSICO')),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Base')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcategoria')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Serviço Disponível',
                'verbose_name_plural': 'Serviços Disponíveis',
                'ordering': ['codigo'],
            },
        ),
    ]
