# Generated by Django 5.1.2 on 2025-09-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0008_servicodisponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamentomedico',
            name='codigo_fechamento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Fechamento'),
        ),
        migrations.AddField(
            model_name='faturamentomedico',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('finalizado', 'Finalizado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
