# Generated by Django 5.1.2 on 2025-09-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0009_faturamentomedico_codigo_fechamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamentomedico',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual da comissão a ser aplicada', max_digits=5, verbose_name='Percentual de Comissão (%)'),
        ),
        migrations.AddField(
            model_name='faturamentomedico',
            name='percentual_imposto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual do imposto a ser aplicado', max_digits=5, verbose_name='Percentual de Imposto (%)'),
        ),
        migrations.AddField(
            model_name='faturamentomedico',
            name='valor_comissao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor calculado da comissão', max_digits=10, verbose_name='Valor da Comissão'),
        ),
        migrations.AddField(
            model_name='faturamentomedico',
            name='valor_imposto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor calculado do imposto', max_digits=10, verbose_name='Valor do Imposto'),
        ),
    ]
