# Generated by Django 5.1.2 on 2025-09-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0010_faturamentomedico_percentual_comissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamentomedico',
            name='apartamento_enfermaria',
            field=models.CharField(blank=True, choices=[('Apartamento', 'Apartamento'), ('Enfermaria', 'Enfermaria')], max_length=20, null=True, verbose_name='Apartamento ou Enfermaria'),
        ),
    ]
