# Generated by Django 5.1.2 on 2025-09-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0011_faturamentomedico_apartamento_enfermaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamentomedico',
            name='urgencia',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=20, null=True, verbose_name='Urgência'),
        ),
    ]
