# Generated by Django 5.1.2 on 2025-09-29 02:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_remove_empresa_anexo_simples'),
        ('faturamento_medico', '0012_faturamentomedico_urgencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Convênio')),
                ('data_lote', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Lote')),
                ('total_lote', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total do Lote')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-data_lote', '-data_criacao'],
            },
        ),
    ]
