# Generated by Django 4.2.2 on 2025-10-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0013_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamentomedico',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('finalizado', 'Finalizado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
