# Generated by Django 5.1.2 on 2025-10-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0014_alter_faturamentomedico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemservico',
            name='percentual',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Percentual a ser aplicado no cálculo (ex: 0.50 para 50%)', max_digits=5, verbose_name='Percentual'),
        ),
    ]
