# Generated by Django 5.1.2 on 2025-10-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0015_itemservico_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamentomedico',
            name='guia_lancada',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Guia Lançada'),
        ),
    ]
