# Generated by Django 5.1.2 on 2025-10-23 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0016_alter_faturamentomedico_guia_lancada'),
    ]

    operations = [
    ]
