# Generated by Django 5.1.2 on 2025-11-01 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0017_auto_20251022_2152'),
    ]

    operations = [
    ]
