# Generated by Django 5.1.2 on 2025-11-04 18:52

import faturamento_medico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0019_auto_20251031_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamentomedico',
            name='data',
            field=models.DateField(default=faturamento_medico.models.data_atual, verbose_name='Data'),
        ),
    ]
