# Generated by Django 4.2.2 on 2026-07-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0027_faturamentomedico_nome_associado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemservico',
            name='status_conferencia',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'PENDENTE'), ('CONFERIDO', 'CONFERIDO'), ('FALTA DE GUIA', 'FALTA DE GUIA'), ('FALTA DE VALOR NA TABELA', 'FALTA DE VALOR NA TABELA'), ('OUTROS', 'OUTROS')], default='PENDENTE', max_length=40, verbose_name='Status Conferência'),
        ),
    ]
