# Generated by Django 5.2.16 on 2026-08-20 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0043_itemservico_status_lote_ok'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='baixado',
            field=models.BooleanField(default=False, help_text='Lote recebido e baixado — oculto na impressão e ao adicionar faturamentos.', verbose_name='Lote baixado'),
        ),
        migrations.CreateModel(
            name='LogStatusConferenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(blank=True, default='', max_length=150, verbose_name='Usuário (nome)')),
                ('status_conferencia', models.CharField(max_length=40, verbose_name='Status Conferência')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('item_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_status_conferencia', to='faturamento_medico.itemservico', verbose_name='Item de serviço')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_status_conferencia_faturamento', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log status conferência',
                'verbose_name_plural': 'Logs status conferência',
                'ordering': ['-data_hora', '-id'],
            },
        ),
    ]
