# Generated by Django 5.2.16 on 2026-08-21 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento_medico', '0044_log_status_conferencia_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemservico',
            name='com_sedacao',
            field=models.BooleanField(default=False, help_text='Exame realizado com sedação/anestesia', verbose_name='Com Sedação'),
        ),
        migrations.CreateModel(
            name='LancamentoAnestesistaExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=200, verbose_name='Médico (anestesista)')),
                ('exame', models.CharField(max_length=200, verbose_name='Exame')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_anestesista', to='faturamento_medico.faturamentomedico', verbose_name='Faturamento')),
                ('item_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_anestesista', to='faturamento_medico.itemservico', verbose_name='Item do exame')),
            ],
            options={
                'verbose_name': 'Lançamento anestesista',
                'verbose_name_plural': 'Lançamentos anestesista',
                'ordering': ['data_criacao', 'id'],
            },
        ),
    ]
