# Generated by Django 4.2.2 on 2023-09-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opcartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tband', models.CharField(max_length=2, verbose_name='tband')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descricao')),
            ],
        ),
    ]
