# Generated by Django 4.2.2 on 2026-07-26 03:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
        ('OPCARTAO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaCartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('SICREDI', 'Sicredi'), ('OUTRO', 'Outro')], default='SICREDI', max_length=20)),
                ('titular', models.CharField(blank=True, default='', max_length=120)),
                ('bandeira', models.CharField(blank=True, default='', max_length=30)),
                ('cartao_final', models.CharField(blank=True, default='', max_length=8)),
                ('referencia_mes', models.CharField(blank=True, default='', max_length=30)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('total_fatura', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('arquivo_nome', models.CharField(blank=True, default='', max_length=255)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas_cartao', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Fatura de cartão',
                'verbose_name_plural': 'Faturas de cartão',
                'ordering': ['-vencimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemFaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.CharField(blank=True, default='', max_length=8)),
                ('cartao_portador', models.CharField(blank=True, default='', max_length=120)),
                ('cartao_final', models.CharField(blank=True, default='', max_length=8)),
                ('cidade', models.CharField(blank=True, default='', max_length=80)),
                ('tipo_compra', models.CharField(blank=True, default='', max_length=20)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('parcela', models.CharField(blank=True, default='', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('pagamento', 'Pagamento'), ('iof', 'IOF')], default='compra', max_length=20)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='OPCARTAO.faturacartaocredito')),
            ],
            options={
                'verbose_name': 'Item da fatura',
                'verbose_name_plural': 'Itens da fatura',
                'ordering': ['data', 'hora', 'id'],
            },
        ),
    ]
