# Generated by Django 4.2.2 on 2026-07-26 03:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
        ('OPCARTAO', '0002_faturacartaocredito_itemfaturacartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturacartaocredito',
            name='banco',
            field=models.CharField(choices=[('SICREDI', 'Sicredi'), ('SICOOB', 'Sicoob'), ('OUTRO', 'Outro')], default='SICREDI', max_length=20),
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição')),
                ('banco', models.CharField(choices=[('SICREDI', 'Sicredi'), ('SICOOB', 'Sicoob'), ('OUTRO', 'Outro')], default='SICREDI', max_length=20)),
                ('bandeira', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('ELO', 'Elo'), ('AMEX', 'American Express'), ('HIPERCARD', 'Hipercard'), ('OUTRA', 'Outra')], default='VISA', max_length=20)),
                ('final_cartao', models.CharField(blank=True, default='', max_length=8, verbose_name='Final do cartão')),
                ('dia_fechamento_fatura', models.PositiveSmallIntegerField(help_text='Dia do mês em que a fatura fecha (ex.: 20).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do fechamento da fatura')),
                ('dia_vencimento_fatura', models.PositiveSmallIntegerField(help_text='Dia do mês em que a fatura vence (ex.: 3).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do vencimento da fatura')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_credito', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Cartão de crédito',
                'verbose_name_plural': 'Cartões de crédito',
                'ordering': ['descricao', 'id'],
            },
        ),
        migrations.AddField(
            model_name='faturacartaocredito',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='OPCARTAO.cartaocredito'),
        ),
    ]
