# Generated by Django 4.2.2 on 2026-07-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPCARTAO', '0003_alter_faturacartaocredito_banco_cartaocredito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturacartaocredito',
            name='perfil_consumo',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='itemfaturacartao',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
