# Generated by Django 4.2.2 on 2026-07-26 03:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPCARTAO', '0004_faturacartaocredito_perfil_consumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaocredito',
            name='limite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Limite total de crédito do cartão.', max_digits=15, verbose_name='Limite do cartão'),
        ),
    ]
