# Generated by Django 4.2.2 on 2026-07-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPCARTAO', '0005_cartaocredito_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturacartaocredito',
            name='cartoes_resumo',
            field=models.JSONField(blank=True, default=list, verbose_name='Resumo por cartão'),
        ),
        migrations.AddField(
            model_name='faturacartaocredito',
            name='conta_cartao',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Conta cartão'),
        ),
    ]
