# Generated by Django 5.1.2 on 2025-10-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('categoria', '0001_initial'),
        ('fornecedor', '0001_initial'),
        ('regrarateio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nota', models.CharField(choices=[('tomador', 'Nota de Tomador'), ('comercio', 'Nota de Comércio')], max_length=20, verbose_name='Tipo de Nota')),
                ('chave_acesso', models.CharField(max_length=44, unique=True, verbose_name='Chave de Acesso')),
                ('numero_nota', models.CharField(max_length=20, verbose_name='Número da Nota')),
                ('serie', models.CharField(max_length=10, verbose_name='Série')),
                ('modelo', models.CharField(default='55', max_length=5, verbose_name='Modelo')),
                ('fornecedor_cnpj', models.CharField(max_length=18, verbose_name='CNPJ Fornecedor')),
                ('fornecedor_nome', models.CharField(max_length=200, verbose_name='Nome Fornecedor')),
                ('destinatario_cnpj', models.CharField(max_length=18, verbose_name='CNPJ Destinatário')),
                ('destinatario_nome', models.CharField(max_length=200, verbose_name='Nome Destinatário')),
                ('data_emissao', models.DateTimeField(verbose_name='Data de Emissão')),
                ('data_saida_entrada', models.DateTimeField(blank=True, null=True, verbose_name='Data Saída/Entrada')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor dos Produtos')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Frete')),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Seguro')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Desconto')),
                ('valor_ii', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do II')),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do IPI')),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do PIS')),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do COFINS')),
                ('valor_icms', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do ICMS')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('importada', 'Importada'), ('processada', 'Processada'), ('erro', 'Erro')], default='importada', max_length=20, verbose_name='Status')),
                ('xml_content', models.TextField(blank=True, verbose_name='Conteúdo XML')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.categoria', verbose_name='Categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedor.fornecedor', verbose_name='Fornecedor Vinculado')),
                ('regra_rateio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regrarateio.regrarateio', verbose_name='Regra de Rateio')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Entrada',
                'verbose_name_plural': 'Notas Fiscais de Entrada',
                'ordering': ['-data_emissao', '-numero_nota'],
                'unique_together': {('empresa', 'chave_acesso')},
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalEntradaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField(verbose_name='Número do Item')),
                ('codigo_produto', models.CharField(max_length=50, verbose_name='Código do Produto')),
                ('ean', models.CharField(blank=True, max_length=20, verbose_name='EAN')),
                ('nome_produto', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('ncm', models.CharField(blank=True, max_length=10, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=10, verbose_name='CEST')),
                ('cfop', models.CharField(max_length=5, verbose_name='CFOP')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor PIS')),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor COFINS')),
                ('valor_icms', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor ICMS')),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor IPI')),
                ('valor_ii', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor II')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.categoria', verbose_name='Categoria')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='notafiscalentrada.notafiscalentrada', verbose_name='Nota Fiscal')),
                ('regra_rateio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regrarateio.regrarateio', verbose_name='Regra de Rateio')),
            ],
            options={
                'verbose_name': 'Item da Nota Fiscal de Entrada',
                'verbose_name_plural': 'Itens da Nota Fiscal de Entrada',
                'ordering': ['numero_item'],
                'unique_together': {('nota_fiscal', 'numero_item')},
            },
        ),
    ]
