# Generated by Django 5.1.2 on 2025-10-26 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscalentrada', '0001_initial'),
        ('formapgto', '0001_initial'),
    ]

    operations = [
        # categoria já existe em 0001_initial; só adicionar forma_pagamento
        migrations.AddField(
            model_name='notafiscalentrada',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formapgto.formapgto', verbose_name='Forma de Pagamento'),
        ),
    ]
