# Generated by Django 5.1.2 on 2025-10-26 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscalentrada', '0002_auto_20251025_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalentrada',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formapgto.formapgto', verbose_name='Forma de Pagamento'),
        ),
    ]
