# Generated by Django 5.1.2 on 2025-10-26 04:16
# forma_pagamento já adicionado em 0002; esta migração era SQL manual para MySQL.
# Mantida como no-op para histórico de migrações.

from django.db import migrations


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscalentrada', '0003_auto_20251025_2310'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
