# Generated by Django 4.2.2 on 2026-02-28 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscalentrada', '0004_auto_20251025_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscalentrada',
            name='regra_rateio',
        ),
    ]
