# Generated by Django 5.2.16 on 2026-09-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
        ('notafiscalentrada', '0006_alter_notafiscalentrada_forma_pagamento_cobranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoComercioFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50)),
                ('nome_produto', models.CharField(blank=True, default='', max_length=200)),
                ('url_imagem', models.URLField(max_length=600)),
                ('fonte', models.CharField(default='openverse', max_length=40)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_produto_comercio', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Foto produto (comércio)',
                'verbose_name_plural': 'Fotos produto (comércio)',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo_produto'), name='produto_comercio_foto_unico_empresa_codigo')],
            },
        ),
    ]
