# Generated by Django 5.1.2 on 2025-11-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_fornecedor_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=20, verbose_name='CNPJ'),
        ),
    ]
