# Generated by Django 4.2.2 on 2026-04-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0003_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('tipo_qualificacao', models.CharField(blank=True, default='', max_length=100, verbose_name='Qualificação')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='fornecedor.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Sócio do fornecedor',
                'verbose_name_plural': 'Sócios do fornecedor',
                'ordering': ['id'],
            },
        ),
    ]
