# Generated by Django 4.2.2 on 2026-04-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0004_socio_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='atividades_cnae',
            field=models.TextField(blank=True, default='', verbose_name='Atividades (CNAE)'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade_uf',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Cidade — UF'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de abertura'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='data_situacao_cadastral',
            field=models.DateField(blank=True, null=True, verbose_name='Data da situação cadastral'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco_eletronico',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Endereço eletrônico (e-mail)'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='logradouro',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='natureza_juridica',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Natureza jurídica'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome fantasia'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='porte',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Porte'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='situacao_cadastral',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Situação cadastral'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='razao',
            field=models.CharField(max_length=200, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
    ]
