# Generated by Django 4.2.2 on 2026-04-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0006_fornecedor_cnpj_normalizar_e_dedup'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fornecedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'cnpj'), name='fornecedor_unico_cnpj_por_empresa'),
        ),
    ]
