# Generated by Django 4.2.2 on 2026-04-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0008_fornecedor_cep_telefone_somente_digitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(help_text='Somente números: CNPJ com 14 dígitos ou CPF com 11 dígitos (pessoa física).', max_length=20, verbose_name='CNPJ / CPF'),
        ),
    ]
