# Generated by Django 4.2.2 on 2026-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0009_fornecedor_cnpj_verbose_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='descricao_extrato_bancario',
            field=models.CharField(blank=True, default='', help_text='Trecho que aparece no histórico do extrato para este CNPJ. Usado na conciliação automática de contas a receber quando CNPJ e nome curto não batem.', max_length=255, verbose_name='Texto no extrato bancário'),
        ),
    ]
