# Generated by Django 4.2.2 on 2025-08-14 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=20, unique=True, verbose_name='Número da Nota')),
                ('serie', models.CharField(max_length=10, verbose_name='Série')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('cnpj_cpf', models.CharField(max_length=18, verbose_name='CNPJ/CPF')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Bruto')),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Líquido')),
                ('discriminacao', models.TextField(verbose_name='Discriminação do Serviço')),
                ('data_cancelamento', models.DateField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('autorizacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autorização')),
                ('forma_pagamento', models.CharField(max_length=100, verbose_name='Forma de Pagamento')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data do Recebimento')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Recebido')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='pendente', max_length=20, verbose_name='Status')),
                ('status_conciliacao', models.CharField(choices=[('nao_conciliado', 'Não Conciliado'), ('conciliado', 'Conciliado'), ('parcialmente_conciliado', 'Parcialmente Conciliado')], default='nao_conciliado', max_length=30, verbose_name='Status de Conciliação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Serviço',
                'verbose_name_plural': 'Notas Fiscais de Serviço',
                'ordering': ['-data_emissao', '-numero_nota'],
            },
        ),
    ]
