# Generated by Django 4.2.2 on 2025-08-14 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapgto', '0003_alter_formapgto_tipo'),
        ('notasfiscais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalservico',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='formapgto.formapgto', verbose_name='Forma de Pagamento'),
        ),
    ]
