# Generated by Django 4.2.2 on 2025-08-14 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_options_empresa_data_atualizacao_and_more'),
        ('notasfiscais', '0002_alter_notafiscalservico_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='discriminacao',
            field=models.TextField(blank=True, null=True, verbose_name='Discriminação'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='numero_nota',
            field=models.CharField(max_length=20, verbose_name='Número da Nota'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Bruto'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Líquido'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Recebido'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscalservico',
            unique_together={('empresa', 'numero_nota')},
        ),
    ]
