# Generated by Django 4.2.2 on 2025-08-15 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0001_initial'),
        ('notasfiscais', '0003_notafiscalservico_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='aliquota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota (%)'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='iss_retido',
            field=models.BooleanField(default=False, verbose_name='ISS Retido'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='outras_retencoes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Outras Retenções'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socio.socio', verbose_name='Sócio Responsável'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='valor_cofins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor COFINS'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='valor_csll',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor CSLL'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='valor_deducoes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Deduções'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='valor_inss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor INSS'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='valor_ir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor IR'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='valor_iss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor ISS'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='valor_iss_retido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor ISS Retido'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='valor_pis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor PIS'),
        ),
    ]
