# Generated by Django 4.2.23 on 2025-08-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0004_notafiscalservico_aliquota_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notafiscalservico',
            old_name='autorizacao',
            new_name='nsu',
        ),
    ]
