# Generated by Django 5.2 on 2025-08-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0005_rename_autorizacao_notafiscalservico_nsu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalservico',
            name='nsu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nsu'),
        ),
    ]
