# Generated by Django 5.2 on 2025-08-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0006_alter_notafiscalservico_nsu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalservico',
            name='status',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='pendente', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='status_conciliacao',
            field=models.CharField(blank=True, choices=[('nao_conciliado', 'Não Conciliado'), ('conciliado', 'Conciliado'), ('parcialmente_conciliado', 'Parcialmente Conciliado')], default='nao_conciliado', max_length=30, null=True, verbose_name='Status de Conciliação'),
        ),
    ]
