# Generated by Django 4.2.23 on 2025-08-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0007_alter_notafiscalservico_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='cofinsapuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cofins'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='pisapuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pis'),
        ),
    ]
