# Generated by Django 4.2.23 on 2025-08-29 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0001_initial'),
        ('notasfiscais', '0008_notafiscalservico_cofinsapuracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalservico',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cobranca.cobranca', verbose_name='Forma de Pagamento'),
        ),
    ]
