# Generated by Django 5.1.2 on 2025-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0009_alter_notafiscalservico_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='csllapuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Csll Apuração'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='irpjadicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Irpj Adicional'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='irpjapuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Irpj Apuração'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='issapuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Iss Apuração'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='cofinsapuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cofins Apuração'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='pisapuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pis Apuração'),
        ),
    ]
