# Generated by Django 5.1.2 on 2025-09-10 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0010_notafiscalservico_csllapuracao_and_more'),
        ('regraImposto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='codigo_da_regra_do_imposto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regraImposto.regraimposto', verbose_name='Código da Regra do Imposto'),
        ),
    ]
