# Generated by Django 5.1.2 on 2025-09-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0011_notafiscalservico_codigo_da_regra_do_imposto'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='base_servico',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('DEMAIS', 'Demais')], default='NORMAL', max_length=10, verbose_name='Base Serviço'),
        ),
    ]
