# Generated by Django 5.1.2 on 2025-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0012_notafiscalservico_base_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='tipo_calculo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('FIXO', 'Fixo')], default='NORMAL', max_length=10, verbose_name='Tipo de Cálculo'),
        ),
    ]
