# Generated by Django 5.1.2 on 2025-09-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0013_notafiscalservico_tipo_calculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscalservico',
            name='status',
        ),
    ]
