# Generated by Django 5.1.2 on 2025-09-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0015_notafiscalservico_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscalservico',
            name='status',
        ),
    ]
