# Generated by Django 5.1.2 on 2025-09-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0016_remove_notafiscalservico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='tipo_de_calculo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('FIXO', 'Fixo'), ('PORCENTAGEM', 'Porcentagem')], default='NORMAL', max_length=20, verbose_name='Tipo de Cálculo'),
        ),
    ]
