# Generated by Django 4.2.23 on 2025-09-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0017_notafiscalservico_tipo_de_calculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscalservico',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='notafiscalservico',
            name='data_recebimento',
        ),
        migrations.RemoveField(
            model_name='notafiscalservico',
            name='valor_recebido',
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='tipo_calculo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('DEMAIS', 'Demais')], default='NORMAL', max_length=10, verbose_name='Tipo de Cálculo'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='tipo_de_calculo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('DEMAIS', 'Demais')], default='NORMAL', max_length=20, verbose_name='Tipo de Cálculo'),
        ),
    ]
