# Generated by Django 4.2.23 on 2025-09-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0018_remove_notafiscalservico_banco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscalservico',
            name='valor_iss',
        ),
    ]
