# Generated by Django 5.1.2 on 2025-09-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0019_remove_notafiscalservico_valor_iss'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='segmento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segmento'),
        ),
    ]
