# Generated by Django 5.1.2 on 2025-09-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0020_notafiscalservico_segmento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscalservico',
            name='tipo_calculo',
        ),
    ]
