# Generated by Django 5.1.2 on 2025-09-19 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0021_remove_notafiscalservico_tipo_calculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscalservico',
            name='tipo_de_calculo',
        ),
    ]
