# Generated by Django 5.1.2 on 2025-09-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0022_add_base_servico_remove_tipo_de_calculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='tipo_de_calculo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('DEMAIS', 'Demais')], default='NORMAL', max_length=20, verbose_name='Tipo de Cálculo'),
        ),
    ]
