# Generated by Django 5.1.2 on 2025-09-22 21:32
# SQL específico para MySQL (INFORMATION_SCHEMA, SET @var, etc.). SQLite: no-op.

from django.db import migrations, connection


def apply_mysql_unique(apps, schema_editor):
    if connection.vendor == "sqlite":
        with connection.cursor() as cursor:
            cursor.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS notasfiscais_notafiscalservico_empresa_numero_nota_serie_unique "
                "ON notasfiscais_notafiscalservico (empresa_id, numero_nota, serie);"
            )
        return
    if connection.vendor != "mysql":
        return
    with connection.cursor() as cursor:
        cursor.execute("""
            SET @constraint_name = (
                SELECT CONSTRAINT_NAME
                FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = 'notasfiscais_notafiscalservico'
                  AND CONSTRAINT_TYPE = 'UNIQUE'
                  AND CONSTRAINT_NAME LIKE '%%empresa%%numero_nota%%'
                LIMIT 1
            );
        """)
        cursor.execute("""
            SET @sql = IF(@constraint_name IS NOT NULL,
                CONCAT('ALTER TABLE notasfiscais_notafiscalservico DROP INDEX ', @constraint_name),
                'SELECT 1'
            );
        """)
        cursor.execute("PREPARE stmt FROM @sql;")
        cursor.execute("EXECUTE stmt;")
        cursor.execute("DEALLOCATE PREPARE stmt;")
        cursor.execute("""
            ALTER TABLE notasfiscais_notafiscalservico
            ADD CONSTRAINT notasfiscais_notafiscalservico_empresa_numero_nota_serie_unique
            UNIQUE (empresa_id, numero_nota, serie);
        """)


def reverse_mysql_unique(apps, schema_editor):
    if connection.vendor != "mysql":
        return
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE notasfiscais_notafiscalservico
            DROP CONSTRAINT IF EXISTS notasfiscais_notafiscalservico_empresa_numero_nota_serie_unique;
        """)
        cursor.execute("""
            ALTER TABLE notasfiscais_notafiscalservico
            ADD CONSTRAINT notasfiscais_notafiscalservico_empresa_numero_nota_unique
            UNIQUE (empresa_id, numero_nota);
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0023_notafiscalservico_tipo_de_calculo'),
    ]

    operations = [
        migrations.RunPython(apply_mysql_unique, reverse_mysql_unique),
    ]
