# Generated by Django 5.1.2 on 2025-09-26 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_empresa_utiliza_iss_fixo'),
        ('notasfiscais', '0024_auto_20250922_1632'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApuracaoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=10, verbose_name='Status')),
                ('adicional_calculado', models.BooleanField(default=False, verbose_name='Adicional Calculado')),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Adicional')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Fechamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
                ('usuario_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Fechamento')),
            ],
            options={
                'verbose_name': 'Apuração de Período',
                'verbose_name_plural': 'Apurações de Período',
                'unique_together': {('empresa', 'data_inicio', 'data_fim')},
            },
        ),
    ]
