# Generated by Django 5.1.2 on 2025-09-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0026_apuracaoperiodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoSimplesNacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.CharField(choices=[('I', 'Anexo I - Comércio'), ('II', 'Anexo II - Indústria'), ('III', 'Anexo III - Serviços'), ('IV', 'Anexo IV - Serviços'), ('V', 'Anexo V - Serviços'), ('VI', 'Anexo VI - Serviços')], max_length=3, verbose_name='Anexo')),
                ('faixa', models.CharField(max_length=10, verbose_name='Faixa')),
                ('limite_inferior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite Inferior (R$)')),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Limite Superior (R$)')),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alíquota (%)')),
                ('valor_deduzir', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor a Deduzir (R$)')),
                ('ano_vigencia', models.IntegerField(default=2024, verbose_name='Ano de Vigência')),
            ],
            options={
                'verbose_name': 'Anexo Simples Nacional',
                'verbose_name_plural': 'Anexos Simples Nacional',
                'ordering': ['anexo', 'faixa'],
                'unique_together': {('anexo', 'faixa', 'ano_vigencia')},
            },
        ),
    ]
