# Generated by Django 5.1.2 on 2025-09-27 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_empresa_anexo_simples_empresa_tem_fator_r'),
        ('notasfiscais', '0028_create_anexo_simples_nacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('total_salario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Salário (R$)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Folha de Salário',
                'verbose_name_plural': 'Folhas de Salário',
                'ordering': ['empresa', 'ano', 'mes'],
                'unique_together': {('empresa', 'ano', 'mes')},
            },
        ),
    ]
