# Generated by Django 4.2.2 on 2025-10-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_remove_empresa_anexo_simples'),
        ('notasfiscais', '0029_anexosimplesnacional_percentual_cofins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexosimplesnacional',
            name='percentual_cofins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='COFINS (%)'),
        ),
        migrations.AddField(
            model_name='anexosimplesnacional',
            name='percentual_cpp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CPP (%)'),
        ),
        migrations.AddField(
            model_name='anexosimplesnacional',
            name='percentual_csll',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CSLL (%)'),
        ),
        migrations.AddField(
            model_name='anexosimplesnacional',
            name='percentual_irpj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='IRPJ (%)'),
        ),
        migrations.AddField(
            model_name='anexosimplesnacional',
            name='percentual_iss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ISS (%)'),
        ),
        migrations.AddField(
            model_name='anexosimplesnacional',
            name='percentual_pis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='PIS (%)'),
        ),
        migrations.AlterField(
            model_name='anexosimplesnacional',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscalservico',
            unique_together={('empresa', 'numero_nota', 'serie')},
        ),
    ]
