# Generated by Django 5.1.2 on 2025-10-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0030_anexosimplesnacional_percentual_cofins_and_more'),
    ]

    operations = [
    ]
