# Generated by Django 5.1.2 on 2025-10-30 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0031_auto_20251029_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogNotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, verbose_name='Número da Nota')),
                ('serie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Série')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('cnpj_cpf', models.CharField(max_length=20, verbose_name='CNPJ/CPF')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Bruto')),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Líquido')),
                ('valor_deducoes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Deduções')),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor PIS')),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor COFINS')),
                ('valor_inss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor INSS')),
                ('valor_ir', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor IR')),
                ('valor_csll', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor CSLL')),
                ('iss_retido', models.BooleanField(default=False, verbose_name='ISS Retido')),
                ('valor_iss_retido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor ISS Retido')),
                ('outras_retencoes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Outras Retenções')),
                ('aliquota', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socio.socio', verbose_name='Sócio')),
                ('discriminacao', models.TextField(blank=True, verbose_name='Discriminação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('segmento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segmento')),
                ('base_servico', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('DEMAIS', 'Demais')], default='NORMAL', max_length=10, verbose_name='Base de Serviço')),
                ('tipo_de_calculo', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('FIXO', 'Fixo')], default='NORMAL', max_length=10, verbose_name='Tipo de Cálculo')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cobranca.cobranca', verbose_name='Forma de Pagamento')),
                ('nsu', models.CharField(blank=True, max_length=100, null=True, verbose_name='NSU')),
                ('status_conciliacao', models.CharField(choices=[('nao_conciliado', 'Não Conciliado'), ('parcialmente_conciliado', 'Parcialmente Conciliado'), ('conciliado', 'Conciliado')], default='nao_conciliado', max_length=30, verbose_name='Status de Conciliação')),
                ('issapuracao', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ISS Apuração')),
                ('pisapuracao', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PIS Apuração')),
                ('cofinsapuracao', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='COFINS Apuração')),
                ('csllapuracao', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='CSLL Apuração')),
                ('irpjapuracao', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IRPJ Apuração')),
                ('irpjadicional', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IRPJ Adicional')),
                ('codigo_da_regra_do_imposto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regraImposto.regraimposto', verbose_name='Regra do Imposto')),
                ('motivo_exclusao', models.CharField(blank=True, max_length=100, verbose_name='Motivo da Exclusão')),
                ('usuario_segmentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', verbose_name='Usuário da Segmentação')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
                ('data_log', models.DateTimeField(auto_now_add=True, verbose_name='Data do Log')),
            ],
            options={
                'verbose_name': 'Log Nota Fiscal',
                'verbose_name_plural': 'Logs Notas Fiscais',
                'ordering': ['-data_log'],
            },
        ),
    ]
