# Generated by Django 5.1.2 on 2025-10-30 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0032_auto_20251029_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lognotafiscal',
            old_name='data_log',
            new_name='data_segmentacao',
        ),
    ]
