# Generated by Django 5.1.2 on 2025-10-30 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0001_initial'),
        ('notasfiscais', '0034_alter_lognotafiscal_observacoes'),
        ('regraImposto', '0007_regraimposto_ha_retencao'),
        ('socio', '0004_socio_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lognotafiscal',
            options={'ordering': ['-data_segmentacao', '-numero_nota'], 'verbose_name': 'Log Nota Fiscal', 'verbose_name_plural': 'Logs Notas Fiscais'},
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='aliquota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota (%)'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='base_servico',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('DEMAIS', 'Demais')], default='NORMAL', max_length=10, verbose_name='Base Serviço'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='cnpj_cpf',
            field=models.CharField(max_length=18, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='codigo_da_regra_do_imposto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regraImposto.regraimposto', verbose_name='Código da Regra do Imposto'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='cofinsapuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cofins Apuração'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='csllapuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Csll Apuração'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='data_segmentacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Segmentação'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='discriminacao',
            field=models.TextField(blank=True, null=True, verbose_name='Discriminação'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cobranca.cobranca', verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='irpjadicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Irpj Adicional'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='irpjapuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Irpj Apuração'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='issapuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Iss Apuração'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='motivo_exclusao',
            field=models.CharField(default='segmentacao', max_length=100, verbose_name='Motivo da Exclusão'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='numero_nota',
            field=models.CharField(max_length=20, verbose_name='Número da Nota'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='outras_retencoes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Outras Retenções'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='pisapuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pis Apuração'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socio.socio', verbose_name='Sócio Responsável'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='status_conciliacao',
            field=models.CharField(blank=True, choices=[('nao_conciliado', 'Não Conciliado'), ('conciliado', 'Conciliado'), ('parcialmente_conciliado', 'Parcialmente Conciliado')], default='nao_conciliado', max_length=30, null=True, verbose_name='Status de Conciliação'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='tipo_de_calculo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('DEMAIS', 'Demais')], default='NORMAL', max_length=20, verbose_name='Tipo de Cálculo'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='usuario_segmentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que segmentou'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Bruto'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='valor_cofins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor COFINS'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='valor_csll',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor CSLL'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='valor_deducoes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Deduções'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='valor_inss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor INSS'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='valor_ir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor IR'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='valor_iss_retido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor ISS Retido'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Líquido'),
        ),
        migrations.AlterField(
            model_name='lognotafiscal',
            name='valor_pis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor PIS'),
        ),
    ]
