# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0035_alter_lognotafiscal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscalservico',
            name='tipo_de_calculo',
        ),
        # LogNotaFiscal é removido na 0037 (outro branch); não remover campo aqui para evitar KeyError ao aplicar após 0038.
    ]
