# Generated by Django 4.2.2 on 2026-02-28 02:24
# Ajustado: criação condicional de Empresa/UsuarioEmpresa; não apagar ApuracaoPeriodo.
# Compatível com db.sqlite (dev) e MySQL (produção) — usa SQL puro por vendor.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_empresa_usuarioempresa_if_missing(apps, schema_editor):
    """Cria tabelas notasfiscais_empresa e notasfiscais_usuarioempresa só se não existirem.
    Usa SQL puro (sem apps.get_model). Compatível com db.sqlite e MySQL."""
    from django.db import connection
    from django.db.utils import OperationalError
    vendor = connection.vendor
    cursor = connection.cursor()
    try:
        if vendor == 'sqlite':
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name='notasfiscais_empresa'"
            )
        elif vendor == 'mysql':
            cursor.execute(
                "SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'notasfiscais_empresa'"
            )
        else:
            cursor.execute(
                "SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'notasfiscais_empresa'"
            )
        if cursor.fetchone():
            return  # tabelas já existem, não criar
    except Exception:
        pass
    try:
        if vendor == 'sqlite':
            schema_editor.execute("""
                CREATE TABLE IF NOT EXISTS notasfiscais_empresa (
                    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                    razao VARCHAR(50) NOT NULL,
                    cnpj VARCHAR(14) NOT NULL,
                    status VARCHAR(7) NOT NULL DEFAULT 'Ativa',
                    nome_fantasia VARCHAR(100) NULL,
                    endereco TEXT NULL,
                    telefone VARCHAR(20) NULL,
                    email VARCHAR(254) NULL,
                    usa_base_calculo_reduzido SMALLINT NOT NULL DEFAULT 0,
                    utiliza_iss_fixo SMALLINT NOT NULL DEFAULT 0,
                    regime_tributario VARCHAR(20) NULL DEFAULT 'LUCRO_REAL',
                    tipo_apuracao VARCHAR(15) NULL DEFAULT 'COMPETENCIA',
                    anexo_i SMALLINT NOT NULL DEFAULT 0,
                    anexo_ii SMALLINT NOT NULL DEFAULT 0,
                    anexo_iii SMALLINT NOT NULL DEFAULT 0,
                    anexo_iv SMALLINT NOT NULL DEFAULT 0,
                    anexo_v SMALLINT NOT NULL DEFAULT 0,
                    tem_fator_r SMALLINT NOT NULL DEFAULT 0,
                    codigo_externo VARCHAR(50) NULL,
                    data_criacao DATETIME NULL,
                    data_atualizacao DATETIME NULL
                )
            """)
            schema_editor.execute("""
                CREATE TABLE IF NOT EXISTS notasfiscais_usuarioempresa (
                    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                    ativo SMALLINT NOT NULL DEFAULT 1,
                    data_criacao DATETIME NOT NULL,
                    representante_legal VARCHAR(255) NOT NULL DEFAULT '',
                    pais VARCHAR(100) NOT NULL DEFAULT '',
                    empresa_id INTEGER NOT NULL REFERENCES notasfiscais_empresa(id) DEFERRABLE INITIALLY DEFERRED,
                    usuario_id INTEGER NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
                    UNIQUE (usuario_id, empresa_id)
                )
            """)
        elif vendor == 'mysql':
            schema_editor.execute("""
                CREATE TABLE IF NOT EXISTS notasfiscais_empresa (
                    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    razao VARCHAR(50) NOT NULL,
                    cnpj VARCHAR(14) NOT NULL,
                    status VARCHAR(7) NOT NULL DEFAULT 'Ativa',
                    nome_fantasia VARCHAR(100) NULL,
                    endereco TEXT NULL,
                    telefone VARCHAR(20) NULL,
                    email VARCHAR(254) NULL,
                    usa_base_calculo_reduzido TINYINT(1) NOT NULL DEFAULT 0,
                    utiliza_iss_fixo TINYINT(1) NOT NULL DEFAULT 0,
                    regime_tributario VARCHAR(20) NULL DEFAULT 'LUCRO_REAL',
                    tipo_apuracao VARCHAR(15) NULL DEFAULT 'COMPETENCIA',
                    anexo_i TINYINT(1) NOT NULL DEFAULT 0,
                    anexo_ii TINYINT(1) NOT NULL DEFAULT 0,
                    anexo_iii TINYINT(1) NOT NULL DEFAULT 0,
                    anexo_iv TINYINT(1) NOT NULL DEFAULT 0,
                    anexo_v TINYINT(1) NOT NULL DEFAULT 0,
                    tem_fator_r TINYINT(1) NOT NULL DEFAULT 0,
                    codigo_externo VARCHAR(50) NULL,
                    data_criacao DATETIME(6) NULL,
                    data_atualizacao DATETIME(6) NULL
                )
            """)
            schema_editor.execute("""
                CREATE TABLE IF NOT EXISTS notasfiscais_usuarioempresa (
                    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    ativo TINYINT(1) NOT NULL DEFAULT 1,
                    data_criacao DATETIME(6) NOT NULL,
                    representante_legal VARCHAR(255) NOT NULL DEFAULT '',
                    pais VARCHAR(100) NOT NULL DEFAULT '',
                    empresa_id BIGINT NOT NULL,
                    usuario_id INT NOT NULL,
                    UNIQUE (usuario_id, empresa_id),
                    FOREIGN KEY (empresa_id) REFERENCES notasfiscais_empresa(id),
                    FOREIGN KEY (usuario_id) REFERENCES auth_user(id)
                )
            """)
        else:
            # PostgreSQL
            schema_editor.execute("""
                CREATE TABLE IF NOT EXISTS notasfiscais_empresa (
                    id BIGSERIAL PRIMARY KEY,
                    razao VARCHAR(50) NOT NULL,
                    cnpj VARCHAR(14) NOT NULL,
                    status VARCHAR(7) NOT NULL DEFAULT 'Ativa',
                    nome_fantasia VARCHAR(100) NULL,
                    endereco TEXT NULL,
                    telefone VARCHAR(20) NULL,
                    email VARCHAR(254) NULL,
                    usa_base_calculo_reduzido BOOLEAN NOT NULL DEFAULT FALSE,
                    utiliza_iss_fixo BOOLEAN NOT NULL DEFAULT FALSE,
                    regime_tributario VARCHAR(20) NULL DEFAULT 'LUCRO_REAL',
                    tipo_apuracao VARCHAR(15) NULL DEFAULT 'COMPETENCIA',
                    anexo_i BOOLEAN NOT NULL DEFAULT FALSE,
                    anexo_ii BOOLEAN NOT NULL DEFAULT FALSE,
                    anexo_iii BOOLEAN NOT NULL DEFAULT FALSE,
                    anexo_iv BOOLEAN NOT NULL DEFAULT FALSE,
                    anexo_v BOOLEAN NOT NULL DEFAULT FALSE,
                    tem_fator_r BOOLEAN NOT NULL DEFAULT FALSE,
                    codigo_externo VARCHAR(50) NULL,
                    data_criacao TIMESTAMP WITH TIME ZONE NULL,
                    data_atualizacao TIMESTAMP WITH TIME ZONE NULL
                )
            """)
            schema_editor.execute("""
                CREATE TABLE IF NOT EXISTS notasfiscais_usuarioempresa (
                    id BIGSERIAL PRIMARY KEY,
                    ativo BOOLEAN NOT NULL DEFAULT TRUE,
                    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL,
                    representante_legal VARCHAR(255) NOT NULL DEFAULT '',
                    pais VARCHAR(100) NOT NULL DEFAULT '',
                    empresa_id BIGINT NOT NULL REFERENCES notasfiscais_empresa(id),
                    usuario_id INTEGER NOT NULL REFERENCES auth_user(id),
                    UNIQUE (usuario_id, empresa_id)
                )
            """)
    except OperationalError as e:
        if 'already exists' not in str(e).lower() and 'duplicate' not in str(e).lower():
            raise


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notasfiscais', '0036_preencher_valor_bruto_com_valor_liquido'),
    ]

    operations = [
        # Estado: registrar Empresa e UsuarioEmpresa
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Empresa',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('razao', models.CharField(max_length=50, verbose_name='Razao')),
                        ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                        ('status', models.CharField(choices=[('Ativa', 'Ativa'), ('Inativa', 'Inativa')], default='Ativa', max_length=7, verbose_name='Estatus')),
                        ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Fantasia')),
                        ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                        ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                        ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                        ('usa_base_calculo_reduzido', models.BooleanField(default=False, verbose_name='Usa Base de Cálculo Reduzido')),
                        ('utiliza_iss_fixo', models.BooleanField(default=False, verbose_name='Utiliza ISS Fixo')),
                        ('regime_tributario', models.CharField(blank=True, choices=[('LUCRO_REAL', 'Lucro Real'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('SIMPLES_NACIONAL', 'Simples Nacional')], default='LUCRO_REAL', max_length=20, null=True, verbose_name='Regime Tributário')),
                        ('tipo_apuracao', models.CharField(blank=True, choices=[('CAIXA', 'Caixa'), ('COMPETENCIA', 'Competência')], default='COMPETENCIA', max_length=15, null=True, verbose_name='Tipo de Apuração')),
                        ('anexo_i', models.BooleanField(default=False, verbose_name='Anexo I')),
                        ('anexo_ii', models.BooleanField(default=False, verbose_name='Anexo II')),
                        ('anexo_iii', models.BooleanField(default=False, verbose_name='Anexo III')),
                        ('anexo_iv', models.BooleanField(default=False, verbose_name='Anexo IV')),
                        ('anexo_v', models.BooleanField(default=False, verbose_name='Anexo V')),
                        ('tem_fator_r', models.BooleanField(default=False, help_text='Apenas para Anexos III e V', verbose_name='Possui Fator R')),
                        ('codigo_externo', models.CharField(blank=True, help_text='Código externo para integração com outros sistemas', max_length=50, null=True, verbose_name='Código Externo')),
                        ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                        ('data_atualizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Atualização')),
                    ],
                    options={
                        'verbose_name': 'Empresa',
                        'verbose_name_plural': 'Empresas',
                        'ordering': ['razao'],
                    },
                ),
                migrations.CreateModel(
                    name='UsuarioEmpresa',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                        ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                        ('representante_legal', models.CharField(blank=True, default='', max_length=255, verbose_name='Representante Legal')),
                        ('pais', models.CharField(blank=True, default='', max_length=100, verbose_name='País')),
                        ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notasfiscais.empresa', verbose_name='Empresa')),
                        ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notasfiscais_usuarioempresa_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                    ],
                    options={
                        'verbose_name': 'Usuário Empresa',
                        'verbose_name_plural': 'Usuários Empresas',
                        'ordering': ['usuario', 'empresa'],
                        'unique_together': {('usuario', 'empresa')},
                    },
                ),
            ],
            database_operations=[],  # tabelas criadas pelo RunPython abaixo (roda depois do state)
        ),
        migrations.RunPython(create_empresa_usuarioempresa_if_missing, noop),
        migrations.RemoveField(
            model_name='lognotafiscal',
            name='codigo_da_regra_do_imposto',
        ),
        migrations.RemoveField(
            model_name='lognotafiscal',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='lognotafiscal',
            name='forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='lognotafiscal',
            name='socio',
        ),
        migrations.RemoveField(
            model_name='lognotafiscal',
            name='usuario_segmentacao',
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Recebido'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='nsu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NSU'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Bruto'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Líquido'),
        ),
        migrations.DeleteModel(
            name='lognotafiscal',
        ),
    ]
