# Generated by Django 4.2.2 on 2026-02-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0037_empresa_usuarioempresa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apuracaoperiodo',
            options={'ordering': ['empresa', 'data_inicio'], 'verbose_name': 'Apuração de Período', 'verbose_name_plural': 'Apurações de Período'},
        ),
    ]
