# Generated by Django 4.2.2 on 2026-07-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0041_notafiscalservico_numero_dps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalservico',
            name='numero_dps',
            field=models.CharField(blank=True, help_text='Número da DPS no XML nacional (nDPS); não confundir com o nNFSe no DANFSE.', max_length=20, null=True, verbose_name='Número da DPS'),
        ),
    ]
