# Generated by Django 4.2.23 on 2025-08-28 00:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cnpj', models.CharField(db_index=True, max_length=14)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=120)),
                ('senha', models.CharField(max_length=255)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cred', to='nfse_rio_branco.company')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('log', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfse_rio_branco.company')),
            ],
        ),
        migrations.CreateModel(
            name='Nfse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_verificacao', models.CharField(blank=True, max_length=64, null=True)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('competencia', models.CharField(blank=True, max_length=7, null=True)),
                ('valor_servico', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('iss_retido', models.BooleanField(default=False)),
                ('prestador_cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('tomador_cnpj_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('xml', models.TextField()),
                ('sha1', models.CharField(max_length=40, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfse_rio_branco.company')),
            ],
            options={
                'unique_together': {('company', 'numero', 'serie')},
            },
        ),
    ]
