# Generated by Django 4.2.23 on 2025-08-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse_rio_branco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcredential',
            name='im',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='portalcredential',
            name='senha_ws',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='portalcredential',
            name='ws_homologa',
            field=models.BooleanField(default=True),
        ),
    ]
