# Generated by Django 4.2.23 on 2025-08-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfse_rio_branco', '0002_portalcredential_im_portalcredential_senha_ws_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalcredential',
            name='im',
        ),
        migrations.RemoveField(
            model_name='portalcredential',
            name='senha_ws',
        ),
        migrations.RemoveField(
            model_name='portalcredential',
            name='ws_homologa',
        ),
    ]
