# Generated by Django 4.2.2 on 2023-09-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao', models.CharField(max_length=50, verbose_name='Razao')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
            ],
        ),
    ]
