# Generated by Django 5.2.16 on 2026-08-01 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaAzulConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Integração ativa')),
                ('ambiente', models.CharField(choices=[('DEV', 'Desenvolvimento'), ('PROD', 'Produção')], default='DEV', max_length=4, verbose_name='Ambiente')),
                ('client_id', models.CharField(blank=True, default='', max_length=120, verbose_name='Client ID')),
                ('client_secret_cifrado', models.TextField(blank=True, default='')),
                ('redirect_uri', models.CharField(blank=True, default='', max_length=500, verbose_name='Redirect URI')),
                ('access_token_cifrado', models.TextField(blank=True, default='')),
                ('refresh_token_cifrado', models.TextField(blank=True, default='')),
                ('token_expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Token expira em')),
                ('oauth_state', models.CharField(blank=True, default='', max_length=64)),
                ('conectado_em', models.DateTimeField(blank=True, null=True, verbose_name='Conectado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_azul_config', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Conta Azul',
                'verbose_name_plural': 'Configurações Conta Azul',
            },
        ),
    ]
