# Generated by Django 4.2.2 on 2026-09-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
        ('dashboard', '0002_geminiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoContaAzul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_azul_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='ID Conta Azul')),
                ('codigo', models.CharField(blank=True, default='', max_length=50, verbose_name='Código')),
                ('descricao', models.CharField(blank=True, default='', max_length=300, verbose_name='Descrição')),
                ('status', models.CharField(blank=True, choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço')),
                ('codigo_cnae', models.CharField(blank=True, default='', max_length=20, verbose_name='CNAE')),
                ('lei_116', models.CharField(blank=True, default='', max_length=20, verbose_name='Lei 116')),
                ('c_class_trib', models.CharField(blank=True, default='', help_text='Código de Classificação Tributária (Reforma Tributária).', max_length=20, verbose_name='cClassTrib')),
                ('codigo_nbs', models.CharField(blank=True, default='', max_length=20, verbose_name='NBS (cNBS)')),
                ('indicador_operacao', models.CharField(blank=True, default='', max_length=20, verbose_name='Indicador da operação')),
                ('aliquota_ibs', models.DecimalField(blank=True, decimal_places=4, help_text='Somente leitura — calculada pelo Conta Azul.', max_digits=7, null=True, verbose_name='Alíquota IBS (%)')),
                ('aliquota_cbs', models.DecimalField(blank=True, decimal_places=4, help_text='Somente leitura — calculada pelo Conta Azul.', max_digits=7, null=True, verbose_name='Alíquota CBS (%)')),
                ('fiscal_pendente_envio', models.BooleanField(default=False, verbose_name='Fiscal pendente de envio')),
                ('importado_em', models.DateTimeField(blank=True, null=True, verbose_name='Importado em')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_conta_azul', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Serviço Conta Azul',
                'verbose_name_plural': 'Serviços Conta Azul',
                'ordering': ['codigo', 'descricao'],
            },
        ),
        migrations.AddConstraint(
            model_name='servicocontaazul',
            constraint=models.UniqueConstraint(condition=models.Q(('conta_azul_id__gt', '')), fields=('empresa', 'conta_azul_id'), name='servico_conta_azul_unico'),
        ),
    ]
