# Generated by Django 5.1.2 on 2025-09-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notasfiscais', '0014_remove_notafiscalservico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Recebido'),
        ),
    ]
