# Generated by Django 4.2.2 on 2023-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formapgto', models.CharField(choices=[('0', 'A VISTA'), ('1', 'A PRAZO')], default='0', max_length=1, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descricao')),
                ('tpag', models.CharField(max_length=3, verbose_name='Tipo Pagto')),
            ],
        ),
    ]
