# Generated by Django 5.1.2 on 2025-10-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='intervaloparcelas',
            field=models.IntegerField(default=30, help_text='Intervalo em dias entre parcelas para pagamentos a prazo', verbose_name='Intervalo Parcelas (dias)'),
        ),
    ]
