# Generated by Django 4.2.2 on 2023-09-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtEmissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissao')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao')),
                ('numdoc', models.CharField(max_length=15, verbose_name='Numero do Documento')),
                ('valorDoc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Documento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria', verbose_name='Categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fornecedor.fornecedor', verbose_name='Fornecedor')),
            ],
        ),
    ]
