# Generated by Django 4.2.2 on 2023-09-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasapagar',
            name='parcela',
            field=models.CharField(default=1, max_length=2, verbose_name='Numero de Parcela'),
            preserve_default=False,
        ),
    ]
