# Generated by Django 4.2.2 on 2023-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0002_contasapagar_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasapagar',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Valor do Desconto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='dtPag',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='dtvenc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Valor do Juros'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Valor da Multa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='valorPago',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Valor Pago'),
            preserve_default=False,
        ),
    ]
