# Generated by Django 4.2.2 on 2023-09-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0003_contasapagar_desconto_contasapagar_dtpag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasapagar',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Desconto'),
        ),
        migrations.AlterField(
            model_name='contasapagar',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Juros'),
        ),
        migrations.AlterField(
            model_name='contasapagar',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor da Multa'),
        ),
        migrations.AlterField(
            model_name='contasapagar',
            name='valorPago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pago'),
        ),
    ]
