# Generated by Django 4.2.2 on 2023-09-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0004_alter_contasapagar_desconto_alter_contasapagar_juros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasapagar',
            name='nossonumero',
            field=models.CharField(default=1, max_length=15, verbose_name='Nosso Numero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='nsu',
            field=models.CharField(default=1, max_length=15, verbose_name='Numero de Autorizacao do Cartao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='obs',
            field=models.CharField(default=1, max_length=250, verbose_name='obs'),
            preserve_default=False,
        ),
    ]
