# Generated by Django 4.2.2 on 2023-09-09 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0001_initial'),
        ('extrato', '0001_initial'),
        ('regrarateio', '0002_regrarateioitem'),
        ('formapgto', '0003_alter_formapgto_tipo'),
        ('contasapagar', '0005_contasapagar_nossonumero_contasapagar_nsu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasapagar',
            name='cobranca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cobranca.cobranca', verbose_name='Cobranca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='contabanco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='extrato.contabancaria', verbose_name='Conta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='formapgto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='formapgto.formapgto', verbose_name='Forma de Pagto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contasapagar',
            name='rateio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='regrarateio.regrarateio', verbose_name='Rateio'),
            preserve_default=False,
        ),
    ]
