# Generated by Django 5.1.2 on 2025-09-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0006_contasapagar_cobranca_contasapagar_contabanco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contasapagar',
            old_name='contabanco',
            new_name='conta_banco',
        ),
    ]
