# Generated by Django 5.1.2 on 2025-10-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0007_auto_20250918_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasapagar',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
