# Generated by Django 5.1.2 on 2025-10-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0009_add_empresa_field'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE contasapagar_contasapagar
            SET empresa_id = 7
            WHERE empresa_id IS NULL OR empresa_id = 1;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
