# Generated by Django 5.1.2 on 2025-10-30 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0010_auto_20251030_0950'),
        ('regrarateio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contasapagar',
            options={'ordering': ['-dtvenc', '-dtEmissao'], 'verbose_name': 'Conta a Pagar', 'verbose_name_plural': 'Contas a Pagar'},
        ),
        migrations.AlterField(
            model_name='contasapagar',
            name='rateio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='regrarateio.regrarateio', verbose_name='Rateio'),
        ),
    ]
