# Generated by Django 5.1.2 on 2025-11-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0011_alter_contasapagar_options_alter_contasapagar_rateio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasapagar',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
    ]
