# Generated by Django 4.2.2 on 2026-03-01 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0003_seed_formas_pagamento_basicas'),
        ('contasapagar', '0013_remove_contasapagar_formapgto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasapagar',
            name='cobranca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cobranca.cobranca', verbose_name='Cobrança / Forma de Pagto'),
        ),
    ]
