# Generated by Django 4.2.2 on 2026-03-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0002_initial'),
        ('contasapagar', '0014_alter_contasapagar_cobranca'),
    ]

    operations = [
    ]
