# Generated by Django 5.2.16 on 2026-08-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0015_merge_0002_initial_0014_alter_contasapagar_cobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasapagar',
            name='conta_azul_parcela_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='ID parcela Conta Azul'),
        ),
    ]
