# Generated by Django 5.2.16 on 2026-09-12 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0012_alter_categoria_grupo'),
        ('contasapagar', '0016_contasapagar_conta_azul_parcela_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasapagar',
            name='centro_custo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='categoria.centrocusto',
                verbose_name='Centro de custo',
            ),
        ),
    ]
