# Generated by Django 4.2.1 on 2023-06-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='socio',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, verbose_name='lastname'),
        ),
        migrations.AddField(
            model_name='socio',
            name='tipo',
            field=models.CharField(default=1, max_length=50, verbose_name='tipo'),
            preserve_default=False,
        ),
    ]
