# Generated by Django 4.2.2 on 2023-08-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0002_socio_email_socio_lastname_socio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='avatarsoc',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/', verbose_name='Imagem'),
        ),
    ]
