# Generated by Django 5.2 on 2025-08-15 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_options_empresa_data_atualizacao_and_more'),
        ('socio', '0003_socio_avatarsoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa'),
        ),
    ]
