# Generated by Django 5.1.2 on 2025-10-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0004_socio_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
