# Generated by Django 5.1.2 on 2025-09-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regraImposto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraimposto',
            name='aliquota_cofins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota COFINS (%)'),
        ),
        migrations.AddField(
            model_name='regraimposto',
            name='aliquota_csll',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota CSLL (%)'),
        ),
        migrations.AddField(
            model_name='regraimposto',
            name='aliquota_irpj',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota IRPJ (%)'),
        ),
        migrations.AddField(
            model_name='regraimposto',
            name='aliquota_pis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota PIS (%)'),
        ),
    ]
