# Generated by Django 5.1.2 on 2025-09-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regraImposto', '0002_regraimposto_aliquota_cofins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraimposto',
            name='percentual_calculo',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Percentual de Cálculo (%)'),
        ),
    ]
