# Generated by Django 5.1.2 on 2025-09-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regraImposto', '0004_regraimposto_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regraimposto',
            name='empresa',
        ),
    ]
