# Generated by Django 5.1.2 on 2025-09-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regraImposto', '0005_remove_regraimposto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraimposto',
            name='aliquota_iss_apuracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota ISS Apuração (%)'),
        ),
    ]
