# Generated by Django 5.1.2 on 2025-09-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regraImposto', '0006_regraimposto_aliquota_iss_apuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraimposto',
            name='ha_retencao',
            field=models.BooleanField(default=False, verbose_name='Há Retenção'),
        ),
    ]
