# Generated by Django 5.1.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_empresa_utiliza_iss_fixo'),
        ('regraImposto', '0007_regraimposto_ha_retencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraimposto',
            name='empresa',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='regras_imposto',
                to='empresa.empresa',
                verbose_name='Empresa'
            ),
        ),
    ]
