# Generated by Django 4.2.2 on 2026-07-23 16:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperativa', models.CharField(blank=True, default='', max_length=200)),
                ('cliente', models.CharField(blank=True, default='', max_length=250)),
                ('numero_contrato', models.CharField(max_length=40, verbose_name='Número do Contrato')),
                ('modalidade', models.CharField(blank=True, default='', max_length=200)),
                ('data_operacao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('prazo_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_contrato', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('taxa_juros_am', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='Taxa juros (% a.m.)')),
                ('taxa_multa_am', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='Taxa multa (% a.m.)')),
                ('taxa_mora_am', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='Taxa mora (% a.m.)')),
                ('indicador_calculo', models.CharField(blank=True, default='Tabela Price', max_length=80, verbose_name='Indicador de cálculo')),
                ('data_extrato', models.DateField(blank=True, null=True, verbose_name='Data do extrato')),
                ('arquivo_origem', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_operacao', '-id'],
                'unique_together': {('empresa', 'numero_contrato')},
            },
        ),
        migrations.CreateModel(
            name='ParcelaEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Nº parcela')),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('amortizacao', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('historico', models.CharField(blank=True, default='', max_length=200)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mora', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('iof', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('status', models.CharField(choices=[('aberta', 'Em aberto'), ('paga', 'Paga'), ('quitada', 'Quitada (simulação)')], default='aberta', max_length=20)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='emprestimos.emprestimo', verbose_name='Empréstimo')),
            ],
            options={
                'verbose_name': 'Parcela de empréstimo',
                'verbose_name_plural': 'Parcelas de empréstimo',
                'ordering': ['numero'],
                'unique_together': {('emprestimo', 'numero')},
            },
        ),
    ]
