# Generated by Django 4.2.2 on 2026-07-23 16:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorCalculoSicoob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField(help_text='Código numérico do indicador no SISBR (ex.: 3, 15).', unique=True, verbose_name='Código Sicoob')),
                ('nome', models.CharField(help_text='Ex.: Tabela Price, Sac Decrescente', max_length=80, verbose_name='Nome')),
                ('rotulo', models.CharField(help_text='Como aparece no PDF: 15-Tabela Price, 3-Sac Decrescente', max_length=100, verbose_name='Rótulo completo')),
                ('tipo', models.CharField(choices=[('price', 'Tabela Price'), ('sac', 'SAC'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo de sistema')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Indicador de cálculo Sicoob',
                'verbose_name_plural': 'Indicadores de cálculo Sicoob',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='indice_correcao',
            field=models.CharField(blank=True, default='', help_text='Ex.: SELIC', max_length=40, verbose_name='Índice de correção'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='indice_correcao_atraso',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Índice de correção atraso'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='pct_correcao_am',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='% de correção (a.m.)'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='pct_correcao_atraso_am',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='% de correção atraso (a.m.)'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='taxa_juros_aa',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Usado em contratos SAC com taxa anual.', max_digits=8, verbose_name='Taxa juros (% a.a.)'),
        ),
        migrations.AddField(
            model_name='parcelaemprestimo',
            name='correcao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Correção (SAC)'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='indicador_calculo',
            field=models.CharField(blank=True, default='', help_text='Texto bruto importado do extrato.', max_length=80, verbose_name='Indicador (texto PDF)'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos', to='emprestimos.indicadorcalculosicoob', verbose_name='Indicador de cálculo'),
        ),
    ]
