# Generated by Django 5.1.2 on 2025-09-10 18:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('empresa', '0001_initial'),
        ('notasfiscais', '0001_initial'),
        ('regrarateio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data do Recebimento')),
                ('valor_a_receber', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor a Receber')),
                ('parcela', models.CharField(default='1/1', max_length=20, verbose_name='Parcela')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Recebido')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.categoria', verbose_name='Categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notasfiscais.notafiscalservico', verbose_name='Nota Fiscal')),
                ('regra_rateio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regrarateio.regrarateio', verbose_name='Regra de Rateio')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-data_vencimento', '-data_emissao'],
            },
        ),
    ]
