# Generated by Django 4.2.2 on 2025-09-16 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('extrato', '0001_initial'),
        ('contasareceber', '0002_remove_contaareceber_banco_contaareceber_conta_banco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaixaContaAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Recebimento')),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Recebido')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('tarifas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarifas')),
                ('tipo_baixa', models.CharField(choices=[('parcial', 'Baixa Parcial'), ('total', 'Baixa Total')], default='total', max_length=10, verbose_name='Tipo de Baixa')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('conta_a_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas', to='contasareceber.contaareceber', verbose_name='Conta a Receber')),
                ('conta_banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extrato.contabancaria', verbose_name='Conta Bancária')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Baixa de Conta a Receber',
                'verbose_name_plural': 'Baixas de Contas a Receber',
                'ordering': ['-data_recebimento', '-data_criacao'],
            },
        ),
    ]
