# Generated by Django 5.1.2 on 2025-09-16 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasareceber', '0003_baixacontaareceber'),
        ('notasfiscais', '0020_notafiscalservico_segmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaareceber',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notasfiscais.notafiscalservico', verbose_name='Nota Fiscal'),
        ),
    ]
