# Generated by Django 5.1.2 on 2025-09-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasareceber', '0004_alter_contaareceber_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaareceber',
            name='doc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento'),
        ),
    ]
