# Generated by Django 5.1.2 on 2025-09-16 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0001_initial'),
        ('contasareceber', '0005_contaareceber_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaareceber',
            name='autorizacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Autorização'),
        ),
        migrations.AddField(
            model_name='contaareceber',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cobranca.cobranca', verbose_name='Forma de Pagamento'),
        ),
    ]
