# Generated by Django 5.1.2 on 2025-09-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasareceber', '0006_contaareceber_autorizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaareceber',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ/CPF'),
        ),
    ]
