# Generated by Django 5.1.2 on 2025-09-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasareceber', '0007_contaareceber_cnpj_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaareceber',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido'), ('cartao', 'Cartão')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
