# Generated by Django 5.1.2 on 2025-10-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contasareceber', '0009_fix_foreign_key_alter_field'),
    ]

    operations = [
    ]
