# Generated by Django 4.2.2 on 2026-03-01 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0003_seed_formas_pagamento_basicas'),
        ('contasareceber', '0010_auto_20251025_1336'),
        ('contasareceber', '0008_alter_contaareceber_status'),  # garante que forma_pagamento já existe (foi adicionado em 0006)
    ]

    operations = [
        migrations.AlterField(
            model_name='contaareceber',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cobranca.cobranca', verbose_name='Cobrança'),
        ),
    ]
