# Generated by Django 4.2.2 on 2026-03-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contasareceber', '0008_alter_contaareceber_status'),
        ('contasareceber', '0011_alter_contaareceber_forma_pagamento'),
    ]

    operations = [
    ]
