# Generated by Django 5.2.16 on 2026-08-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasareceber', '0014_contaareceber_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaareceber',
            name='conta_azul_parcela_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='ID parcela Conta Azul'),
        ),
    ]
