# Generated by Django 4.2.2 on 2025-05-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao', models.CharField(max_length=50, verbose_name='Razao')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('status', models.CharField(max_length=7, verbose_name='Estatus')),
            ],
        ),
    ]
