# Generated by Django 4.2.2 on 2025-06-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Inativa', 'Inativa')], default='Ativa', max_length=7, verbose_name='Estatus'),
        ),
    ]
