# Generated by Django 5.1.2 on 2025-09-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_options_empresa_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usa_base_calculo_reduzido',
            field=models.BooleanField(default=False, verbose_name='Usa Base de Cálculo Reduzido'),
        ),
    ]
