# Generated by Django 5.1.2 on 2025-09-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_empresa_usa_base_calculo_reduzido'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='utiliza_iss_fixo',
            field=models.BooleanField(default=False, verbose_name='Utiliza ISS Fixo'),
        ),
    ]
