# Generated by Django 5.1.2 on 2025-09-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_empresa_utiliza_iss_fixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='regime_tributario',
            field=models.CharField(blank=True, choices=[('LUCRO_REAL', 'Lucro Real'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('SIMPLES_NACIONAL', 'Simples Nacional')], default='LUCRO_REAL', max_length=20, null=True, verbose_name='Regime Tributário'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_apuracao',
            field=models.CharField(blank=True, choices=[('CAIXA', 'Caixa'), ('COMPETENCIA', 'Competência')], default='COMPETENCIA', max_length=15, null=True, verbose_name='Tipo de Apuração'),
        ),
    ]
