# Generated by Django 5.1.2 on 2025-09-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_empresa_regime_tributario_empresa_tipo_apuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='anexo_simples',
            field=models.CharField(blank=True, choices=[('I', 'Anexo I - Comércio'), ('II', 'Anexo II - Indústria'), ('III', 'Anexo III - Serviços'), ('IV', 'Anexo IV - Serviços'), ('V', 'Anexo V - Serviços')], max_length=3, null=True, verbose_name='Anexo Simples Nacional'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tem_fator_r',
            field=models.BooleanField(default=False, help_text='Apenas para Anexos III e V', verbose_name='Possui Fator R'),
        ),
    ]
