# Generated by Django 5.1.2 on 2025-09-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_empresa_anexo_simples_empresa_tem_fator_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='anexo_i',
            field=models.BooleanField(default=False, verbose_name='Anexo I'),
        ),
    ]
