# Generated by Django 5.1.2 on 2025-09-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_empresa_anexo_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='anexo_ii',
            field=models.BooleanField(default=False, verbose_name='Anexo II'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='anexo_iii',
            field=models.BooleanField(default=False, verbose_name='Anexo III'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='anexo_iv',
            field=models.BooleanField(default=False, verbose_name='Anexo IV'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='anexo_v',
            field=models.BooleanField(default=False, verbose_name='Anexo V'),
        ),
    ]
