# Generated by Django 5.1.2 on 2025-09-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_empresa_anexo_ii_empresa_anexo_iii_empresa_anexo_iv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='anexo_simples',
        ),
    ]
