# Generated by Django 5.1.2 on 2025-10-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_remove_empresa_anexo_simples'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_externo',
            field=models.CharField(blank=True, help_text='Código externo para integração com outros sistemas', max_length=50, null=True, verbose_name='Código Externo'),
        ),
    ]
