# Generated by Django 4.2.2 on 2026-04-18 22:58

from django.db import migrations, models
import empresa.models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_empresa_nfse_nacional_pfx_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nfse_nacional_pfx_arquivo',
            field=models.FileField(blank=True, help_text='Envie o arquivo pelo navegador; fica salvo no servidor (pasta media/).', max_length=500, upload_to=empresa.models._empresa_pfx_nacional_upload_to, verbose_name='Certificado digital (.pfx)'),
        ),
    ]
