"""
Django settings for SaudeFinanceira project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from django.contrib.messages import constants
from pathlib import Path

from SaudeFinanceira.google_grpc_env import silenciar_logs_grpc_google

silenciar_logs_grpc_google()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv_file() -> None:
    """Carrega .env local (gitignored) sem sobrescrever variáveis já definidas."""
    env_path = BASE_DIR / '.env'
    if not env_path.is_file():
        return
    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


_load_dotenv_file()

# Postgres local (opcional): USE_POSTGRES=true + POSTGRES_DB=SaudeFinanceiraPessoal
# Render / produção: DATABASE_URL ou arquivo render_db.url (gitignored)
if not os.environ.get('DATABASE_URL', '').strip():
    _render_db_url = BASE_DIR / 'render_db.url'
    if _render_db_url.is_file():
        os.environ.setdefault(
            'DATABASE_URL',
            _render_db_url.read_text(encoding='utf-8').strip(),
        )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-i*t9-j%j_57l=(qr6^bj^b%ela@muq4xmqq0hp#=q%j_dxf!)_',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Com DEBUG=False o runserver não expõe /static/ (helper static() em urls fica vazio) — CSS/JS 404.
# Em produção: DJANGO_DEBUG=false + collectstatic + whitenoise.
# No Render, DEBUG deve ser false (WhiteNoise serve staticfiles/ via collectstatic).
_on_render = os.environ.get('RENDER', '').strip().lower() in ('true', '1', 'yes')
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
if _render_host or _on_render:
    DEBUG = False
else:
    _debug_env = os.environ.get('DJANGO_DEBUG', 'true').lower()
    DEBUG = _debug_env in ('true', '1', 'yes')

_default_hosts = [
    'localhost', '127.0.0.1', '[::1]', '10.10.1.151', '192.168.1.2', '192.168.1.10',
    'DESKTOP-8KU7E4Q', '10.10.1.61', '10.10.1.106', '192.168.1.24',
    'django01.intra.local', '.onrender.com',
    'financaspessoais-eloo.onrender.com',
    'saudefinanceira-pessoal.onrender.com',
]
_env_hosts = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]
if _render_host and _render_host not in _env_hosts:
    _env_hosts.append(_render_host)
ALLOWED_HOSTS = list(dict.fromkeys(_default_hosts + _env_hosts))

if DEBUG:
    import socket
    try:
        for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            ip = info[4][0]
            if ip and ip not in ALLOWED_HOSTS:
                ALLOWED_HOSTS.append(ip)
    except OSError:
        pass

_default_csrf_origins = [
    'https://financaspessoais-eloo.onrender.com',
    'https://saudefinanceira-pessoal.onrender.com',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://192.168.1.2:8000',
]
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get('CSRF_TRUSTED_ORIGINS', ','.join(_default_csrf_origins)).split(',')
    if o.strip() and '*' not in o.strip()
] or _default_csrf_origins

if _render_host:
    _render_origin = f'https://{_render_host}'
    if _render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_render_origin)

if DEBUG:
    for host in ALLOWED_HOSTS:
        if host.startswith('.') or host in ('localhost', '[::1]'):
            continue
        origin = f'http://{host}:8000'
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Login real em /login/ (accounts.urls); o padrão do Django é /accounts/login/ (404 neste projeto)
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/empresa/lista/'



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
   
    'socio',
    'categoria',
    'formapgto',  # Mantido só para migrations; tabela será removida pela migration 0005
    'cobranca',
    'OPCARTAO',
    'regrarateio',
    'regraImposto',
    'cliente',
    'fornecedor',
    'contasapagar',
    'usuario',
    'django_table_sort',
    'accounts',
    'django_bootstrap5',
    'empresa',
    'notasfiscais',
    'relatoriorecebiveis',
    'extrato',
    'contasareceber.apps.ContasareceberConfig',
    'faturamento_medico',
    'servicos_medicos',
    'fluxo_de_caixa',
    'notafiscalentrada',
    'regraConciliacao',
    'emprestimos',
    'planejamento_orcamentario',
    'agendador_tarefas',
    'indicadores',
    



]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'notasfiscais.middleware.HandleSessionInterruptedMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'notasfiscais.middleware.ClearNFSeFiltersOnLeaveMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'whitenoise.middleware.WhiteNoiseMiddleware',
    # 'empresa.middleware.EmpresaMiddleware',
]
#STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'SaudeFinanceira.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'SaudeFinanceira.context_processors.cotacao_context',
                'agendador_tarefas.context_processors.tarefas_letreiro',
                'usuario.context_processors.menu_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'SaudeFinanceira.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # Sync Conta Azul / OneDrive: evita OperationalError "database is locked"
        'OPTIONS': {
            'timeout': 60,
        },
    }
}

_database_url = os.environ.get('DATABASE_URL', '').strip()
if _database_url:
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(
        default=_database_url,
        conn_max_age=600,
        ssl_require=_database_url.startswith('postgres'),
    )

    def _completar_host_postgres_render(db_settings):
        """
        Desenvolvimento local: URL copiada do Render às vezes traz host curto (dpg-xxx-a).
        Completa com o sufixo regional público para conectar de fora do Render.
        No Render (DATABASE_URL interna), o host curto é correto — não alterar.
        """
        host = (db_settings.get('HOST') or '').strip()
        if not host.startswith('dpg-') or '.' in host:
            return db_settings
        if _on_render:
            return db_settings
        suffix = os.environ.get(
            'RENDER_PG_HOST_SUFFIX',
            'oregon-postgres.render.com',
        ).strip().lstrip('.')
        if suffix:
            db_settings['HOST'] = f'{host}.{suffix}'
        return db_settings

    DATABASES['default'] = _completar_host_postgres_render(DATABASES['default'])
elif os.environ.get('USE_POSTGRES', '').strip().lower() in ('1', 'true', 'yes'):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'SaudeFinanceiraPessoal').strip() or 'SaudeFinanceiraPessoal',
        'USER': os.environ.get('POSTGRES_USER', 'postgres').strip() or 'postgres',
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost').strip() or 'localhost',
        'PORT': os.environ.get('POSTGRES_PORT', '5432').strip() or '5432',
        'CONN_MAX_AGE': 600,
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = "America/Rio_Branco"
USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATE_INPUT_FORMATS = ['%Y-%m-%d', '%d/%m/%Y']

# Backups completos do banco (somente admin / superuser)
_backup_dir_env = os.environ.get('BACKUP_DATABASE_DIR', '').strip()
BACKUP_DATABASE_DIR = Path(_backup_dir_env) if _backup_dir_env else BASE_DIR / 'backups'
BACKUP_DATABASE_TIMEOUT = 600


MESSAGE_TAGS = {
    constants.ERROR: 'alert-danger',
    constants.WARNING: 'alert-warning',
    constants.DEBUG: 'alert-info',
    constants.SUCCESS: 'alert-success',
}
STATIC_URL = '/static/'
STATICFILES_DIRS = [
                   BASE_DIR / "static",
]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATIC_ROOT = BASE_DIR / "staticfiles"
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
MEDIA_URL = '/media/'
# Uploads (anexos, certificados). Local: media/ no projeto.
# Render: disco persistente em /var/data/media (render.yaml) — sobrevive a redeploys.
_media_root_env = (os.environ.get('MEDIA_ROOT') or '').strip()
if _media_root_env:
    MEDIA_ROOT = _media_root_env
elif _on_render or _render_host:
    MEDIA_ROOT = '/var/data/media'
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Storage S3/R2 (opcional, futuro): USE_S3_STORAGE=true + django-storages + AWS_* no Render.
# Enquanto inativo, anexos usam FileField em MEDIA_ROOT (Render Disk /var/data/media).
USE_S3_STORAGE = os.environ.get('USE_S3_STORAGE', '').strip().lower() in ('1', 'true', 'yes')
if USE_S3_STORAGE:
    # Requer: pip install django-storages[boto3] e variáveis AWS_STORAGE_BUCKET_NAME, etc.
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', '') or None

# NFS-e ambiente nacional (SEFIN), mTLS com certificado A1 (.pfx) no servidor.
# Variáveis de ambiente (opcionais; por empresa ver campos em Empresa):
#   NFSE_NACIONAL_BASE_URL — produção: https://sefin.nfse.gov.br | homologação: https://sefin.producaorestrita.nfse.gov.br
#   NFSE_NACIONAL_PFX_PATH — caminho absoluto do .pfx
#   NFSE_NACIONAL_PFX_PASSWORD — senha do PFX
#   NFSE_NACIONAL_VERIFY_SSL — true/false
#   NFSE_NACIONAL_CONNECT_TIMEOUT — segundos para abrir TCP/TLS (padrão 120)
#   NFSE_NACIONAL_READ_TIMEOUT — segundos para corpo da resposta (padrão 180)
#   NFSE_NACIONAL_HTTP_RETRIES — tentativas extras em timeout/conexão (padrão 2)
NFSE_NACIONAL = {
    "base_url": os.environ.get(
        "NFSE_NACIONAL_BASE_URL",
        "https://sefin.producaorestrita.nfse.gov.br",
    ),
    "pfx_path": os.environ.get("NFSE_NACIONAL_PFX_PATH", ""),
    "pfx_password": os.environ.get("NFSE_NACIONAL_PFX_PASSWORD", ""),
    "verify_ssl": os.environ.get("NFSE_NACIONAL_VERIFY_SSL", "true").lower() in ("1", "true", "yes"),
    "connect_timeout": float(os.environ.get("NFSE_NACIONAL_CONNECT_TIMEOUT", "120")),
    "read_timeout": float(os.environ.get("NFSE_NACIONAL_READ_TIMEOUT", "180")),
    "max_retries": int(os.environ.get("NFSE_NACIONAL_HTTP_RETRIES", "2")),
}

# ADN (Ambiente de Dados Nacional) — distribuição de documentos por NSU.
# Permite sincronizar NFSe em massa (sem conhecer DPS/chave de cada nota).
# Ajuste os endpoints conforme o manual vigente do ambiente:
#   produção: https://adn.nfse.gov.br
#   homologação: https://adn.producaorestrita.nfse.gov.br
#
# API oficial (SDK nfse-php): GET {base}/contribuintes/DFe/{nsu}
#   • CNPJ (14 dígitos): query opcional cnpjConsulta (o app envia automaticamente).
#   • CPF (11 dígitos): não usar cnpjConsulta — identificação só pelo certificado (E2242 se enviar).
# Variáveis de ambiente (exemplo):
#   ADN_NFSE_BASE_URL=https://adn.nfse.gov.br
#   ADN_NFSE_DISTRIBUICAO_PATHS=/contribuintes/DFe
#   ADN_NFSE_ULTIMO_NSU_PATHS=/contribuintes/DFe
#   ADN_NFSE_VERIFY_SSL=true
# Homologação: ADN_NFSE_BASE_URL=https://adn.producaorestrita.nfse.gov.br
# O path /contribuintesissqn/DFe não existe em produção (HTTP 404) — é ignorado se estiver no .env.


def _adn_nfse_paths_csv(env_key: str, default_csv: str) -> list[str]:
    """Lista de prefixos de path; remove entradas inválidas conhecidas e duplicatas."""
    raw = os.environ.get(env_key, default_csv)
    bad = frozenset({"/contribuintesissqn/DFe".lower(), "/contribuintesissqn/dfe".lower()})
    seen: set[str] = set()
    out: list[str] = []
    for part in raw.split(","):
        p = part.strip()
        if not p:
            continue
        if not p.startswith("/"):
            p = "/" + p
        if p.lower() in bad:
            continue
        if p in seen:
            continue
        seen.add(p)
        out.append(p)
    return out or ["/contribuintes/DFe"]


ADN_NFSE = {
    "base_url": os.environ.get("ADN_NFSE_BASE_URL", "https://adn.nfse.gov.br"),
    "verify_ssl": os.environ.get("ADN_NFSE_VERIFY_SSL", "true").lower() in ("1", "true", "yes"),
    # Prefixo (sem o NSU final): GET {base}{prefix}/{nsu} (cnpjConsulta só para CNPJ — ver doc acima).
    "distribuicao_paths": _adn_nfse_paths_csv(
        "ADN_NFSE_DISTRIBUICAO_PATHS",
        "/contribuintes/DFe",
    ),
    "ultimo_nsu_paths": _adn_nfse_paths_csv(
        "ADN_NFSE_ULTIMO_NSU_PATHS",
        "/contribuintes/DFe",
    ),
    # Janela retroativa (NSU) só para bootstrap do cursor; não reconsultar desde 0 quando já há NSU salvo.
    "retro_window_nsu": int(os.environ.get("ADN_NFSE_RETRO_WINDOW_NSU", "200") or "200"),
    # Quantas rodadas de GET /DFe encadear a partir do último NSU (avanço na fila).
    "fetch_rounds": int(os.environ.get("ADN_NFSE_FETCH_ROUNDS", "25") or "25"),
    # Com filtro por período, relê uma janela recente de NSU (evita perder notas novas no portal).
    "period_scan_window_nsu": int(os.environ.get("ADN_NFSE_PERIOD_SCAN_WINDOW_NSU", "1200") or "1200"),
}

# Cópia em disco dos XML importados (preenchendo também nas pastas da empresa em cadastro).
# Prestador: {NFSE_XML_COPIA_PRESTADOR ou Empresa.nfse_xml_pasta_prestador}/{codigo}-{razão tomador}/{MMYYYY}/arquivo.xml
# Tomador:   {NFSE_XML_COPIA_TOMADOR ou Empresa.nfse_xml_pasta_tomador}/{codigo}-{razão prestador}/{MMYYYY}/arquivo.xml
# Canceladas (checkbox na importação): .../{MMYYYY}/Cancelada/arquivo.xml
# Subpastas {codigo}-{razão} e MMYYYY são criadas automaticamente se não existirem.
# Exemplo (variável de ambiente ou cadastro da empresa): X:\MASTER\PREFEITURA - ARQUIVOS 2.0\1-RIO BRANCO\2026\PRESTADOS
NFSE_XML_COPIA_PRESTADOR = os.environ.get("NFSE_XML_COPIA_PRESTADOR", "").strip()
NFSE_XML_COPIA_TOMADOR = os.environ.get("NFSE_XML_COPIA_TOMADOR", "").strip()

# POST «executar Selenium» na tela Portal (extensão): dispara manage.py nesta máquina (Windows: novo console).
# Desative em servidor Linux remoto sem display: NFSE_PORTAL_PLAYWRIGHT_HTTP=false
NFSE_PORTAL_PLAYWRIGHT_HTTP = os.environ.get("NFSE_PORTAL_PLAYWRIGHT_HTTP", "true").lower() in (
    "1",
    "true",
    "yes",
)

# Opcional: ajuste se o portal mudar (Selenium lê esta mesma chave).
# Sem persistent_context: perfil temporário a cada execução. Com True: Chrome/Edge com user-data-dir dedicado.
# Pasta perfil vazia → ~/.saude_financeira/playwright_nfse_profile (mesmo nome que antes; pode alterar em persistent_user_data_dir).
# NFSE_PORTAL_PLAYWRIGHT = {
#     "persistent_context": True,
#     "browser_channel": "chrome",  # ou "msedge"
#     "persistent_user_data_dir": "",
#     "emitidas_page_url": "https://www.nfse.gov.br/EmissorNacional/Notas/Emitidas",
#     "after_login_emitidas_url": "",
#     "emitidas_max_linhas": 500,  # total em todas as páginas
#     "emitidas_max_linhas_por_pagina": 250,  # por iteração na grelha
#     "emitidas_max_paginas": 80,  # limite de segurança ao clicar «seguinte»
#     # Se o Selenium falhar no login: inspecione o campo no portal e defina:
#     # "user_selectors": ["#seuCampoUsuario"],
#     # "password_selector": 'input[type="password"]',
#     # "submit_selectors": ['button:has-text("Entrar")'],  # ou seletor CSS válido
#     Downloads Selenium vão para PRESTADOS/{codigo}-{razão}/{MMYYYY}/ (mês único); emitidas_download_inbox_subdir deixou de ser usado.
# }
NFSE_PORTAL_PLAYWRIGHT: dict = {"persistent_context": False}

# Link da extensão «Baixar NFSe» (Chrome Web Store) — usado na tela de importação pelo portal.
_nfse_baixar_url = os.environ.get("NFSE_PORTAL_NFSE_BAIXAR_WEBSTORE_URL", "").strip()
NFSE_PORTAL_NFSE_BAIXAR_WEBSTORE_URL = (
    _nfse_baixar_url or "https://chromewebstore.google.com/detail/enehmclajcndmgefbmjhecccoegbdgea"
)

NFSE_RIO_BRANCO_WS = {
"version": "2.03", # ou "1.02" conforme sua opção
"endpoint_municipal": "https://nota.riobranco.ac.gov.br/ws",
"endpoint_nacional": "https://www.sefazvirtual.com.br/nfse/ws/NfseServices4",  # Base nacional ABRASF
   #https://nota.riobranco.ac.gov.br/ws/nfse203.wsdl
# SSL: use True, False ou caminho para CA/chain obtidos em "Certificados SSL"
"verify_ssl": False,
}

# API Key Google Gemini — .env local e variável no Render
# Após comprar créditos: use chave nova do projeto com faturamento (chave gratuita mantém limite ~20/dia)
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "").strip()
# Tesseract OCR (Windows: caminho completo se não estiver no PATH)
TESSERACT_CMD = os.environ.get("TESSERACT_CMD", "").strip()
# Modelo Gemini (com créditos: gemini-2.5-flash — igual ao app desktop Renome)
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash").strip() or "gemini-2.5-flash"
# Configurações de upload de arquivos
DATA_UPLOAD_MAX_NUMBER_FILES = 1000  # Limite de arquivos para importação XML
# Renomear guias / importações: vários PDFs por requisição (Render + Django default 2,5 MB estoura)
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100 MB — corpo total da requisição
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB por arquivo antes de ir para disco temporário

# Depuração da importação NFSe: logs detalhados de forma_pagamento/discriminacao (só quando True)
NFS_IMPORT_DEBUG = os.environ.get("NFS_IMPORT_DEBUG", "false").lower() in ("1", "true", "yes")

# API Sicoob — extrato (Conta Corrente v4). Client ID no portal desenvolvedor.
# Token OAuth (grant password): no POST, "username" = chave de acesso (PJ) ou usuário (PF); "password" = senha.
# Apps confidenciais no Keycloak exigem também SICOOB_CLIENT_SECRET (mesmo valor do dashboard).
SICOOB_CLIENT_ID = os.environ.get("SICOOB_CLIENT_ID", "")
SICOOB_CLIENT_SECRET = os.environ.get("SICOOB_CLIENT_SECRET", "")
SICOOB_TOKEN_URL = os.environ.get(
    "SICOOB_TOKEN_URL",
    "https://auth.sicoob.com.br/auth/realms/cooperado/protocol/openid-connect/token",
)
SICOOB_API_BASE = os.environ.get("SICOOB_API_BASE", "https://api.sicoob.com.br/conta-corrente/v4")
# PJ: use SICOOB_CHAVE_ACESSO + SICOOB_SENHA (recomendado). PF/legado: SICOOB_USERNAME + SICOOB_PASSWORD.
SICOOB_CHAVE_ACESSO = os.environ.get("SICOOB_CHAVE_ACESSO", "")
SICOOB_SENHA = os.environ.get("SICOOB_SENHA", "")
SICOOB_USERNAME = os.environ.get("SICOOB_USERNAME", "")
SICOOB_PASSWORD = os.environ.get("SICOOB_PASSWORD", "")
SICOOB_SCOPE = os.environ.get("SICOOB_SCOPE", "openid cco_extrato")
# Documentação Sicoob: OAuth 2.0 client credentials (RFC 6749) + mTLS + Client ID.
# Use "password" apenas se o ambiente ainda aceitar resource owner password (legado).
SICOOB_TOKEN_GRANT = os.environ.get("SICOOB_TOKEN_GRANT", "client_credentials").strip().lower()
# Só desenvolvimento: se o portal não liberar grant password, cole aqui um access_token JWT válido
# (expira em minutos; obtenha por outro meio homologado pelo Sicoob). Deixe vazio em produção.
SICOOB_ACCESS_TOKEN = os.environ.get("SICOOB_ACCESS_TOKEN", "")
# mTLS na URL de token (e na API de extrato): certificado cliente obrigatório em produção.
# Opção A: par PEM — SICOOB_MTLS_CERT + SICOOB_MTLS_KEY (caminhos absolutos).
# Opção B: PKCS#12 — SICOOB_MTLS_PFX + SICOOB_MTLS_PFX_PASSWORD.
# Na empresa: marcar "Sicoob — mTLS com o mesmo PFX da NFS-e nacional" reutiliza o .pfx (upload ou caminho no servidor) + senha.
SICOOB_MTLS_CERT = os.environ.get("SICOOB_MTLS_CERT", "")
SICOOB_MTLS_KEY = os.environ.get("SICOOB_MTLS_KEY", "")
SICOOB_MTLS_PFX = os.environ.get("SICOOB_MTLS_PFX", "")
SICOOB_MTLS_PFX_PASSWORD = os.environ.get("SICOOB_MTLS_PFX_PASSWORD", "")


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TEMPLATE_CONTEXT_PROCESSORS  =  (
    'django.template.context_processors.request' ,
)

# Log JSON completo do extrato Sicoob no terminal (runserver). Em produção use false (dados sensíveis).
SICOOB_LOG_EXTRATO_JSON = os.environ.get(
    "SICOOB_LOG_EXTRATO_JSON",
    "true" if DEBUG else "false",
).lower() in ("1", "true", "yes")

# Garante que logs de openfinanceSicoob e do app extrato apareçam no console (antes ficavam só em logger sem handler).
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console_sicoob": {
            "format": "[%(levelname)s] %(asctime)s %(name)s: %(message)s",
            "datefmt": "%H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console_sicoob",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "OPCARTAO": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "SaudeFinanceira.openfinanceSicoob": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "extrato": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
