# Generated by Django 5.2.16 on 2026-10-06 18:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0024_alter_empresa_nfse_portal_nacional_login'),
        ('estoque', '0002_quantidade_estoque_contabil'),
        ('fornecedor', '0012_fornecedor_conta_azul_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('cotacao', 'Em cotação'), ('concluido', 'Concluído')], default='rascunho', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_compra_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_compra', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Orçamento de compra',
                'verbose_name_plural': 'Orçamentos de compra',
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoCompraFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(help_text='Rótulo da coluna (ex.: razão social ou apelido).', max_length=200, verbose_name='Nome na tabela')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('pdf_orcamento', models.FileField(blank=True, null=True, upload_to='orcamento_compra/pdf/%Y/%m/', verbose_name='PDF do fornecedor')),
                ('pdf_texto', models.TextField(blank=True, default='', verbose_name='Texto extraído do PDF')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_compra_colunas', to='fornecedor.fornecedor', verbose_name='Fornecedor')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='orcamento_compra.orcamentocompra', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Fornecedor (coluna)',
                'verbose_name_plural': 'Fornecedores (colunas)',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='Produto / descrição')),
                ('unidade', models.CharField(blank=True, default='UN', max_length=20, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=14, verbose_name='Quantidade')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamento_compra.orcamentocompra', verbose_name='Orçamento')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_compra_itens', to='estoque.produtoestoque', verbose_name='Produto (estoque)')),
            ],
            options={
                'verbose_name': 'Item do orçamento',
                'verbose_name_plural': 'Itens do orçamento',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoCompraPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Preço unitário')),
                ('preco_total', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional; se vazio, usa quantidade × unitário.', max_digits=14, null=True, verbose_name='Preço total')),
                ('observacao', models.CharField(blank=True, default='', max_length=255, verbose_name='Obs.')),
                ('coluna_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='orcamento_compra.orcamentocomprafornecedor', verbose_name='Fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='orcamento_compra.orcamentocompraitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Preço cotado',
                'verbose_name_plural': 'Preços cotados',
                'constraints': [models.UniqueConstraint(fields=('item', 'coluna_fornecedor'), name='orcamento_preco_item_fornecedor_unico')],
            },
        ),
    ]
