# Generated by Django 5.2.16 on 2026-10-06 18:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento_compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoCompraResultadoVencedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('total_geral', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Total')),
                ('coluna_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_vencedores', to='orcamento_compra.orcamentocomprafornecedor', verbose_name='Fornecedor')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_vencedores', to='orcamento_compra.orcamentocompra', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Orçamento vencedor (fornecedor)',
                'verbose_name_plural': 'Orçamentos vencedores (fornecedor)',
                'ordering': ['coluna_fornecedor__ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoCompraResultadoVencedorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='Produto')),
                ('unidade', models.CharField(default='UN', max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=14)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('preco_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitorias_resultado', to='orcamento_compra.orcamentocompraitem', verbose_name='Item original')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamento_compra.orcamentocompraresultadovencedor', verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Item do orçamento vencedor',
                'verbose_name_plural': 'Itens do orçamento vencedor',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='orcamentocompraresultadovencedor',
            constraint=models.UniqueConstraint(fields=('orcamento', 'coluna_fornecedor'), name='orcamento_vencedor_unico_por_coluna'),
        ),
    ]
