# Generated by Django 5.1.2 on 2025-10-25 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0010_remove_empresa_anexo_simples'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFluxoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('lucro_prejuizo', 'Lucro ou Prejuízo'), ('investimentos', 'Investimentos'), ('distribuicao_lucro', 'Distribuição de Lucro'), ('resultado_final', 'Resultado Final')], max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaFluxoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo_de_caixa.categoriafluxocaixa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'unique_together': {('categoria', 'ano', 'mes', 'empresa')},
            },
        ),
    ]
