# Generated by Django 4.2.2 on 2023-09-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegraRateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomedaregra', models.CharField(max_length=30, verbose_name='Regra')),
                ('rateio', models.CharField(choices=[('S', 'SIM'), ('N', 'NAO')], default='S', max_length=1, verbose_name='Rateio')),
            ],
        ),
    ]
