# Generated by Django 4.2.2 on 2023-09-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0001_initial'),
        ('regrarateio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraRateioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percRateio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual Rateio')),
                ('regrarateio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regrarateio.regrarateio')),
                ('socios', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='socio.socio')),
            ],
        ),
    ]
