# Generated by Django 4.2.2 on 2026-04-10 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contasapagar', '0015_merge_0002_initial_0014_alter_contasapagar_cobranca'),
        ('empresa', '0012_socio'),
        ('contasareceber', '0013_alter_contaareceber_forma_pagamento'),
        ('socio', '0005_socio_cpf'),
        ('regrarateio', '0002_regrarateioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='regrarateio',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='regrarateio',
            name='nomedaregra',
            field=models.CharField(max_length=30, verbose_name='Descrição da regra'),
        ),
        migrations.CreateModel(
            name='LancamentoRateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento / recebimento')),
                ('tipo', models.CharField(choices=[('PGTO', 'Pagamento'), ('RECEBIMENTO', 'Recebimento')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_rateio', to='contasapagar.contasapagar', verbose_name='Conta a pagar')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_rateio', to='contasareceber.contaareceber', verbose_name='Conta a receber')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
                ('regra_rateio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regrarateio.regrarateio', verbose_name='Regra de rateio')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socio.socio', verbose_name='Sócio')),
            ],
            options={
                'verbose_name': 'Lançamento de rateio',
                'verbose_name_plural': 'Lançamentos de rateio',
                'ordering': ['-data_pagamento', '-id'],
                'indexes': [models.Index(fields=['empresa', '-data_pagamento'], name='regrarateio_empresa_30ad26_idx'), models.Index(fields=['conta_pagar'], name='regrarateio_conta_p_bc9b10_idx'), models.Index(fields=['conta_receber'], name='regrarateio_conta_r_0a9117_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='lancamentorateio',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('conta_pagar__isnull', False), ('conta_receber__isnull', True)), models.Q(('conta_pagar__isnull', True), ('conta_receber__isnull', False)), _connector='OR'), name='lancamento_rateio_cap_ou_car'),
        ),
    ]
