# Generated by Django 4.2.2 on 2026-04-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regrarateio', '0004_regrarateio_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regrarateio',
            options={'ordering': ['empresa_id', 'nomedaregra'], 'verbose_name': 'Regra de rateio', 'verbose_name_plural': 'Regras de rateio'},
        ),
        migrations.AddIndex(
            model_name='regrarateio',
            index=models.Index(fields=['empresa', 'nomedaregra'], name='regrarateio_empresa_f0dd66_idx'),
        ),
    ]
