# Generated by Django 5.2.16 on 2026-09-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regrarateio', '0006_regrarateio_modo_alocacao_regrarateioitem_tipo_participacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentorateio',
            name='modalidade',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='lancamentorateio',
            name='obs',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Obs.'),
        ),
        migrations.AddField(
            model_name='lancamentorateio',
            name='obs_forma',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Obs. forma'),
        ),
        migrations.AddField(
            model_name='lancamentorateio',
            name='origem',
            field=models.CharField(blank=True, choices=[('PAGAR', 'Pagar'), ('RECEBER', 'Receber'), ('IMPORTACAO', 'IMPORTACAO')], default='', max_length=12, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='lancamentorateio',
            name='viabilidade',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Viabilidade'),
        ),
        migrations.AlterField(
            model_name='regrarateio',
            name='rateio',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NAO')], default='S', help_text='SIM: divide o valor entre sócios. NÃO: não gera lançamentos de rateio.', max_length=1, verbose_name='Rateio'),
        ),
    ]
